import type {
  ChoiceQuestion,
  CodeQuestion,
  CurriculumCatalog,
  Skill,
  Unit,
} from '../curriculum';

const courseId = 'python-data-analysis';
const choice = (
  prompt: string,
  choices: string[],
  answer: number,
  explanation: string,
  hint: string,
  code?: string,
): Omit<ChoiceQuestion, 'id'> => ({
  type: 'choice',
  prompt,
  choices,
  answer,
  explanation,
  hint,
  ...(code ? { code } : {}),
});
const exercise = (
  prompt: string,
  starterCode: string,
  solution: string,
  tests: string,
  explanation: string,
  hint: string,
): Omit<CodeQuestion, 'id'> => ({
  type: 'code',
  prompt,
  starterCode,
  solution,
  tests,
  explanation,
  hint,
});
function skill(
  id: string,
  unitId: string,
  title: string,
  summary: string,
  prerequisites: string[],
  paragraphs: string[],
  code: string,
  output: string,
  explanation: string,
  questions: (Omit<ChoiceQuestion, 'id'> | Omit<CodeQuestion, 'id'>)[],
  cards: [string, string][],
): Skill {
  return {
    id,
    courseId,
    domain: 'programming',
    unitId,
    title,
    summary,
    prerequisites,
    order: 0,
    estimatedMinutes: 10,
    assessment: { requiredTypes: ['code', 'choice'], reviewAnswers: 2 },
    lesson: { paragraphs, example: { code, output, explanation } },
    questions: questions.map((question, index) => ({
      ...question,
      id: id + '-q' + (index + 1),
    })),
    flashcards: cards.map(([front, back], index) => ({
      id: id + '-card' + (index + 1),
      skillId: id,
      front,
      back,
    })),
  };
}

const units: Unit[] = [
  {
    id: 'da-numpy',
    courseId,
    title: 'Numerical arrays',
    description: 'Use shape, vectorization, selection, and broadcasting.',
  },
  {
    id: 'da-pandas',
    courseId,
    title: 'Labeled tables',
    description: 'Build and select data with pandas.',
  },
  {
    id: 'da-cleaning',
    courseId,
    title: 'Load and clean',
    description: 'Read text data and make quality decisions explicit.',
  },
  {
    id: 'da-wrangling',
    courseId,
    title: 'Connect and reshape',
    description: 'Normalize text, encode categories, join, and reshape.',
  },
  {
    id: 'da-grouping',
    courseId,
    title: 'Summarize groups',
    description: 'Aggregate, transform, and calculate moving summaries.',
  },
  {
    id: 'da-analysis',
    courseId,
    title: 'Build an analysis',
    description:
      'Handle dates, explore evidence, and produce a repeatable result.',
  },
];

const skills: Skill[] = [
  skill(
    'da-arrays',
    'da-numpy',
    'Create numerical arrays',
    'Turn Python sequences into arrays with an explicit shape and data type.',
    ['nested-lists', 'imports', 'tuples'],
    [
      'A NumPy array stores values in a grid with a shared data type. Import the package with import numpy as np, then call np.array(...) with a Python list. Unlike a list, an ordinary numeric array supports arithmetic on all its entries.',
      'shape is a tuple containing the length of each axis. A flat array of three values has shape (3,); two rows with three values each have shape (2, 3). size counts all entries, while ndim counts axes. dtype describes their representation. Use dtype=float when decimal calculations are expected.',
      'Inspect the shape before calculating: rows might represent observations and columns might represent measurements. NumPy stores dimensions, not their meaning; your analysis supplies that meaning. tolist() converts a small array into ordinary Python values for readable output.',
    ],
    'import numpy as np\nmeasurements = np.array([[12, 18, 24], [15, 21, 27]])\nprint(measurements.shape)\nprint(measurements.size)\nprint(measurements.tolist())',
    '(2, 3)\n6\n[[12, 18, 24], [15, 21, 27]]',
    'Two equally sized inner lists become two rows and three columns.',
    [
      choice(
        'An array has shape (4, 2). How many entries does it contain?',
        ['4', '2', '8', '6'],
        2,
        'There are four rows of two values, so size is 4 × 2 = 8.',
        'Multiply the axis lengths.',
      ),
      choice(
        'What does ndim count?',
        [
          'The number of axes',
          'The largest value',
          'The number of missing values',
          'Bytes per entry',
        ],
        0,
        'A one-dimensional array has one axis; a matrix has two.',
        'It describes the structure of the grid.',
      ),
      choice(
        'Which construction explicitly supports decimal values?',
        [
          'np.array([1, 2], dtype=int)',
          'np.array([1, 2], dtype=float)',
          '[1, 2].shape',
          'np.shape(float)',
        ],
        1,
        'dtype=float chooses a floating-point representation for every entry.',
        'Look for the requested dtype.',
      ),
      exercise(
        'Create an array called readings containing two rows: [3, 5, 7] and [4, 6, 8]. Store its shape in dimensions and its entry count in count.',
        'import numpy as np\n# Create readings, dimensions, and count.\n',
        'import numpy as np\nreadings = np.array([[3, 5, 7], [4, 6, 8]])\ndimensions = readings.shape\ncount = readings.size',
        'assert isinstance(readings, np.ndarray), "Create a NumPy array."\nassert readings.tolist() == [[3, 5, 7], [4, 6, 8]], "Keep the two requested rows."\nassert dimensions == (2, 3), "Read the shape attribute."\nassert count == 6, "Read the size attribute."',
        'np.array creates the grid; shape and size describe it without changing its entries.',
        'Pass a nested list to np.array, then access readings.shape and readings.size.',
      ),
    ],
    [
      [
        'What do NumPy shape, size, and ndim describe?',
        'shape: length of each axis; size: total entries; ndim: number of axes.',
      ],
      [
        'How do you create a floating-point NumPy array from a list?',
        'import numpy as np, then np.array(values, dtype=float).',
      ],
    ],
  ),

  skill(
    'da-vectorization',
    'da-numpy',
    'Calculate by column',
    'Apply arithmetic to complete arrays and reduce along an axis.',
    ['da-arrays', 'math-mean', 'parameters'],
    [
      'Vectorized arithmetic applies an operation to every entry. With a numeric NumPy array, values * 2 doubles values; with a Python list, values * 2 repeats the list. An array expression usually returns a new array, so save that result in a variable.',
      'sum and mean can reduce a whole array to one value. On a two-dimensional array, axis=0 combines rows and leaves one result per column; axis=1 combines columns and leaves one result per row. The reduced axis disappears from the result.',
      "Reduction choice should match the question. If rows are shops and columns are days, sum(axis=1) gives each shop's total, while sum(axis=0) gives each day's total across shops. Always connect axes to the dataset's meaning.",
    ],
    'import numpy as np\norders = np.array([[2, 4], [6, 8]])\nprint((orders * 3).tolist())\nprint(orders.sum(axis=0).tolist())\nprint(orders.mean(axis=1).tolist())',
    '[[6, 12], [18, 24]]\n[8, 12]\n[3.0, 7.0]',
    'Arithmetic keeps the grid; each reduction removes one axis.',
    [
      choice(
        'What does np.array([2, 5]) * 2 produce?',
        ['[2, 5, 2, 5]', 'An error', '[4, 10]', '[2, 10]'],
        2,
        'Array multiplication scales entries rather than repeating a sequence.',
        'NumPy numeric arithmetic is element-wise.',
      ),
      choice(
        'Rows are branches and columns are months. Which operation totals each branch?',
        ['sales.sum(axis=0)', 'sales.sum(axis=1)', 'sales.shape', 'sales.ndim'],
        1,
        'axis=1 reduces the month columns within each branch row.',
        'Keep one result per row.',
      ),
      choice(
        'What is the output?',
        ['[8, 12]', '[6, 14]', '20', '[2, 4, 6, 8]'],
        0,
        'axis=0 combines corresponding column entries: 2+6 and 4+8.',
        'Reduce downward through the rows.',
        'import numpy as np\na = np.array([[2, 4], [6, 8]])\nprint(a.sum(axis=0).tolist())',
      ),
      exercise(
        'The rows of sales are stores, and its columns are days. Make doubled by doubling every entry, and daily_totals containing the total for each day.',
        'import numpy as np\nsales = np.array([[3, 7, 5], [8, 2, 4]])\n# Create doubled and daily_totals.\n',
        'import numpy as np\nsales = np.array([[3, 7, 5], [8, 2, 4]])\ndoubled = sales * 2\ndaily_totals = sales.sum(axis=0)',
        'assert isinstance(doubled, np.ndarray) and doubled.tolist() == [[6, 14, 10], [16, 4, 8]], "Double every sale."\nassert isinstance(daily_totals, np.ndarray) and daily_totals.tolist() == [11, 9, 9], "Produce one total for each day."\nassert sales.tolist() == [[3, 7, 5], [8, 2, 4]], "Preserve the source array."',
        'Element-wise arithmetic and axis=0 reduction answer two different questions from the same grid.',
        'Use sales * 2 and sales.sum(axis=0).',
      ),
    ],
    [
      [
        'How does array * 2 differ from list * 2?',
        'A numeric array doubles each entry; a list repeats its sequence.',
      ],
      [
        'For a 2D array, what do sum(axis=0) and sum(axis=1) return?',
        'axis=0: one sum per column. axis=1: one sum per row.',
      ],
    ],
  ),

  skill(
    'da-array-indexing',
    'da-numpy',
    'Select array entries',
    'Combine two-axis indexing, boolean masks, and explicit copies.',
    ['da-vectorization', 'slicing'],
    [
      'Select a matrix entry with array[row, column]. A colon selects a range along an axis, so array[:, 1] selects the second column across all rows. Positions start at zero; a slice stops before its ending position, just as it does for a Python list.',
      'A comparison such as values >= 10 creates an array of booleans. values[mask] returns entries whose positions are True. On a matrix, a one-dimensional row mask selects entire rows when used as matrix[mask].',
      'Basic NumPy slices usually share the original storage. Changing a sliced view can change the source array. Call .copy() when you need an independent selection. Boolean indexing makes a copy; knowing the distinction prevents accidental changes to raw measurements.',
    ],
    'import numpy as np\nreadings = np.array([[5, 9], [12, 8], [7, 15]])\nprint(readings[:, 1].tolist())\nmask = readings[:, 0] >= 7\nprint(readings[mask].tolist())',
    '[9, 8, 15]\n[[12, 8], [7, 15]]',
    'Select a column to form the row condition, then use its boolean mask to select rows.',
    [
      choice(
        'Which expression selects the first column of every row?',
        ['a[0, :]', 'a[:, 0]', 'a[1]', 'a[:, 1]'],
        1,
        'The colon spans rows; column position zero selects the first column.',
        'The row selector comes first.',
      ),
      choice(
        'What does a[a > 4] select from a one-dimensional array?',
        [
          'Its first four entries',
          'All entries greater than four',
          'Four random entries',
          'The position numbered four',
        ],
        1,
        'The comparison generates a mask, and True positions are retained.',
        'The brackets receive booleans, not a count.',
      ),
      choice(
        'You will modify a basic slice without changing the source. What should you do?',
        [
          'Use .copy() on the slice',
          'Use a larger slice',
          'Rename the variable',
          'Print it first',
        ],
        0,
        'A basic slice can be a view; an explicit copy owns independent data.',
        'Changing a name does not copy the storage.',
      ),
      exercise(
        'Create selected containing rows whose first value is at least 10. Also create independent as a copy of the second column. Leave values unchanged.',
        'import numpy as np\nvalues = np.array([[8, 2], [14, 5], [10, 7]])\n# Create selected and independent.\n',
        'import numpy as np\nvalues = np.array([[8, 2], [14, 5], [10, 7]])\nselected = values[values[:, 0] >= 10]\nindependent = values[:, 1].copy()',
        'assert selected.tolist() == [[14, 5], [10, 7]], "Filter whole rows using the first column."\nassert independent.tolist() == [2, 5, 7], "Select the second column."\nassert not np.shares_memory(independent, values), "Create an independent copy."\nassert values.tolist() == [[8, 2], [14, 5], [10, 7]], "Keep raw values unchanged."',
        'A row mask selects observations; .copy() protects the original matrix from later edits.',
        'Build a mask from values[:, 0], and call .copy() on values[:, 1].',
      ),
    ],
    [
      [
        'How do you select all rows of column 1 in a NumPy matrix?',
        'matrix[:, 1] (positions start at zero).',
      ],
      [
        'Why call .copy() on a NumPy basic slice before modifying it?',
        'Basic slices can share storage with the original array; a copy separates the data.',
      ],
    ],
  ),

  skill(
    'da-broadcasting',
    'da-numpy',
    'Match shapes for arithmetic',
    'Use broadcasting deliberately instead of relying on accidental dimensions.',
    ['da-array-indexing'],
    [
      'Broadcasting lets arrays with compatible shapes participate in element-wise arithmetic. NumPy compares dimensions from right to left: each pair must be equal, or one must be 1. Missing leading dimensions act like 1. A scalar can therefore combine with any array.',
      'An array shaped (rows, columns) plus a vector shaped (columns,) adds the vector to each row. A vector with one value per row must become a column, such as offsets[:, None], before adding it across columns. None inserts a length-one axis.',
      'Check the resulting shape before trusting a calculation. Broadcasting can expand both inputs into a larger output; compatible dimensions do not guarantee that your operation has the intended meaning. For example, (3, 1) plus (3,) produces (3, 3), not (3, 1).',
    ],
    'import numpy as np\nlevels = np.array([[2, 4, 6], [3, 5, 7]])\nadjustments = np.array([10, 20, 30])\nprint((levels + adjustments).tolist())\nprint((levels + np.array([100, 200])[:, None]).tolist())',
    '[[12, 24, 36], [13, 25, 37]]\n[[102, 104, 106], [203, 205, 207]]',
    'A column-length vector adjusts columns; a reshaped row-length vector adjusts rows.',
    [
      choice(
        'Which shapes can be added directly by broadcasting?',
        [
          '(2, 3) and (2,)',
          '(2, 3) and (3,)',
          '(2, 3) and (4,)',
          '(2,) and (3,)',
        ],
        1,
        'The trailing dimension three matches; the leading missing dimension behaves as one.',
        'Compare from the right.',
      ),
      choice(
        'What shape results from (3, 1) plus (3,)?',
        ['(3,)', '(3, 1)', '(1, 3)', '(3, 3)'],
        3,
        'The vector acts as (1, 3), so broadcasting expands both singleton axes.',
        'Write the second shape as (1, 3).',
      ),
      choice(
        'A row offset vector has shape (4,). How can you add it to a (4, 2) matrix by row?',
        [
          'matrix + offsets',
          'matrix + offsets[:, None]',
          'matrix + offsets[None, :]',
          'matrix * 0',
        ],
        1,
        'offsets[:, None] has shape (4, 1), compatible with (4, 2).',
        'The trailing dimension must be one or two.',
      ),
      exercise(
        'Each row is a day and each column is a sensor. Add the sensor calibration [1, -2, 3] to every row, storing calibrated.',
        'import numpy as np\nreadings = np.array([[10, 20, 30], [15, 25, 35]])\ncalibration = np.array([1, -2, 3])\n# Create calibrated using array arithmetic.\n',
        'import numpy as np\nreadings = np.array([[10, 20, 30], [15, 25, 35]])\ncalibration = np.array([1, -2, 3])\ncalibrated = readings + calibration',
        'assert isinstance(calibrated, np.ndarray), "Keep an array result."\nassert calibrated.shape == (2, 3), "Keep the original shape."\nassert calibrated.tolist() == [[11, 18, 33], [16, 23, 38]], "Apply the matching offset to each sensor column."',
        'The three-element calibration aligns with the three sensor columns and repeats across days.',
        'The shapes (2, 3) and (3,) are already compatible.',
      ),
    ],
    [
      [
        'What makes two NumPy dimensions compatible for broadcasting?',
        'Compare right to left: matching lengths or a length of 1; absent leading dimensions act like 1.',
      ],
      [
        'How do you turn a length-n vector into a column for broadcasting?',
        'vector[:, None], with shape (n, 1).',
      ],
    ],
  ),

  skill(
    'da-series',
    'da-pandas',
    'Use labeled values',
    'Construct a pandas Series and distinguish labels from positions.',
    ['da-vectorization', 'dictionaries'],
    [
      'Import pandas as pd. A Series pairs one-dimensional values with an index of labels. pd.Series([8, 12], index=["north", "south"]) gives each number a meaningful name. You can also create a Series from a dictionary: its keys become index labels.',
      'Use .loc[label] to select by label and .iloc[position] to select by zero-based position. This distinction matters when labels themselves are integers: a label of 10 is not position 10. Explicit .loc and .iloc make your intention readable.',
      'A Series supports arithmetic and reductions such as .sum(). Its .index holds the labels; .tolist() exposes the values for a small example. Labels should identify what each value describes, rather than relying on unexplained positions.',
    ],
    'import pandas as pd\nvisits = pd.Series([14, 22, 9], index=["east", "west", "central"])\nprint(visits.loc["west"])\nprint(visits.iloc[0])\nprint(visits.sum())',
    '22\n14\n45',
    'Label selection and positional selection can name the same value in different ways.',
    [
      choice(
        'In pd.Series([4, 7], index=[10, 20]), what does .iloc[0] return?',
        ['10', '20', '4', '7'],
        2,
        'iloc selects position zero, which holds the value four.',
        'Ignore the index labels for positional selection.',
      ),
      choice(
        'Which selection explicitly looks up the label north?',
        ['s.iloc["north"]', 's.loc["north"]', 's.shape["north"]', 's.index(0)'],
        1,
        'loc selects by index label.',
        'Use the label-oriented accessor.',
      ),
      choice(
        'When constructing a Series from a dictionary, what becomes its index?',
        [
          'Dictionary values',
          'Only the first key',
          'Dictionary keys',
          'A random sequence',
        ],
        2,
        'Each dictionary key labels its associated value.',
        'A mapping already has named entries.',
      ),
      exercise(
        'Create stock as a Series with labels pen and notebook and values 12 and 7. Store the notebook value in notebooks and the first value by position in first.',
        'import pandas as pd\n# Create stock, notebooks, and first.\n',
        'import pandas as pd\nstock = pd.Series([12, 7], index=["pen", "notebook"])\nnotebooks = stock.loc["notebook"]\nfirst = stock.iloc[0]',
        'assert isinstance(stock, pd.Series), "Create a pandas Series."\nassert stock.to_dict() == {"pen": 12, "notebook": 7}, "Use the requested labels and values."\nassert notebooks == 7, "Select notebook by label."\nassert first == 12, "Select the first position."',
        'The labels describe items, while position zero describes their order.',
        'Use pd.Series(..., index=...), then .loc and .iloc.',
      ),
    ],
    [
      [
        'How do pandas .loc and .iloc differ?',
        '.loc selects index labels; .iloc selects zero-based positions.',
      ],
      [
        'What is a pandas Series?',
        'A one-dimensional collection of values with an associated index of labels.',
      ],
    ],
  ),

  skill(
    'da-dataframes',
    'da-pandas',
    'Build a table',
    'Represent observations as rows and named variables as columns.',
    ['da-series'],
    [
      'A DataFrame is a table with row labels and named columns. pd.DataFrame({"item": ["pen", "bag"], "price": [2, 9]}) combines columns of equal length. Unlike a numerical array, different columns can have different data types.',
      'table["price"] selects one column as a Series. table[["item", "price"]] selects a DataFrame with specified columns; the extra brackets represent a list of names. table.shape gives (row_count, column_count), and table.head(n) previews the first n rows.',
      'Assigning table["new_name"] = expression adds or replaces a column. A calculation like table["units"] * table["price"] aligns corresponding rows and computes one result per observation. Choose explicit column names and a consistent row meaning.',
    ],
    'import pandas as pd\norders = pd.DataFrame({"item": ["pen", "bag"], "units": [3, 2], "price": [2, 9]})\norders["total"] = orders["units"] * orders["price"]\nprint(orders.shape)\nprint(orders["total"].tolist())',
    '(2, 4)\n[6, 18]',
    'Each row describes an order; the derived total column contains its units multiplied by its price.',
    [
      choice(
        'What does table["amount"] normally return?',
        [
          'A Series',
          'A list of column names',
          'A tuple',
          'A scalar for the whole table',
        ],
        0,
        'A single named column is a Series indexed by the table rows.',
        'One column is one-dimensional.',
      ),
      choice(
        'How do you select two columns while keeping a DataFrame?',
        [
          'table["a", "b"]',
          'table[["a", "b"]]',
          'table.iloc["a", "b"]',
          'table.shape[0]',
        ],
        1,
        'Pass a list of column names inside the selection brackets.',
        'The inner brackets construct the list of names.',
      ),
      choice(
        'A DataFrame has shape (5, 3). What does one row represent in a tidy observational table?',
        [
          'All columns of one observation',
          'All observations of one variable',
          'A column name only',
          'A NumPy data type',
        ],
        0,
        'Rows represent observations, and columns describe their variables.',
        'Separate observation count from variable count.',
      ),
      exercise(
        'Create orders from the supplied columns. Add revenue as units times price and save just item and revenue as summary.',
        'import pandas as pd\ncolumns = {"item": ["book", "lamp"], "units": [4, 2], "price": [6, 11]}\n# Create orders, then summary.\n',
        'import pandas as pd\ncolumns = {"item": ["book", "lamp"], "units": [4, 2], "price": [6, 11]}\norders = pd.DataFrame(columns)\norders["revenue"] = orders["units"] * orders["price"]\nsummary = orders[["item", "revenue"]]',
        'assert isinstance(orders, pd.DataFrame) and orders.shape == (2, 4), "Create the table and derived column."\nassert orders["revenue"].tolist() == [24, 22], "Multiply units by price per row."\nassert isinstance(summary, pd.DataFrame), "Keep a table result."\nassert summary.to_dict("list") == {"item": ["book", "lamp"], "revenue": [24, 22]}, "Select the requested columns in order."',
        'A DataFrame gives columns a shared observation index while allowing separate data types.',
        'Construct pd.DataFrame(columns), assign revenue, then select a list of column names.',
      ),
    ],
    [
      [
        'How do you select a pandas column as a Series versus a DataFrame?',
        'table["name"] returns a Series; table[["name"]] returns a DataFrame.',
      ],
      [
        'How do you add a derived DataFrame column?',
        'Assign table["new_column"] = an expression producing one value per row.',
      ],
    ],
  ),

  skill(
    'da-label-alignment',
    'da-pandas',
    'Align by identity',
    'Understand automatic index alignment and explicit reindexing.',
    ['da-series'],
    [
      'pandas arithmetic aligns labels, rather than blindly matching positions. If two Series list the same locations in different orders, addition still combines values for the same location. This is useful when independently collected datasets share stable identifiers.',
      'When a label exists on only one side, ordinary addition produces a missing result for it. .add(other, fill_value=0) can treat that absent side as zero when this matches the business meaning. Missing measurements are not automatically zero; make that decision explicitly.',
      '.reindex([...]) requests labels in a specific order and inserts missing values for absent labels. Alignment and reindexing are about identity, not sorting values. When you deliberately want positional NumPy operations, first verify order before converting to arrays.',
    ],
    'import pandas as pd\na = pd.Series([4, 8], index=["red", "blue"])\nb = pd.Series([3, 7], index=["blue", "red"])\nprint((a + b).reindex(["red", "blue"]).tolist())\nprint(a.reindex(["blue", "red"]).tolist())',
    '[11, 11]\n[8, 4]',
    'The red values add to 11, and the blue values add to 11, despite different input orders.',
    [
      choice(
        'Series a has labels [x, y], and b has [y, x]. How does a + b match entries?',
        [
          'By their positions only',
          'By matching index labels',
          'By the smaller value',
          'It always raises an error',
        ],
        1,
        'pandas pairs values sharing the same index label.',
        'The index carries identity.',
      ),
      choice(
        'What does reindex(["b", "a"]) do to labels ["a", "b"]?',
        [
          'Sorts values ascending',
          'Renames both labels',
          'Returns rows ordered b then a',
          'Deletes the index',
        ],
        2,
        'reindex specifies the desired label order.',
        'The list describes the result index.',
      ),
      choice(
        'One Series lacks label z. When is add(..., fill_value=0) appropriate?',
        [
          'Whenever data is missing',
          'When an absent contribution genuinely means zero',
          'Only for strings',
          'To prove the measurement was observed',
        ],
        1,
        'Zero filling is a semantic decision: absence of a contribution can mean zero, but an unobserved measurement need not.',
        'Think about what absence means in the dataset.',
      ),
      exercise(
        'Combine counts from two channels by matching product labels. An absent channel contribution means zero. Store totals ordered pen, bag, mug.',
        'import pandas as pd\nshop = pd.Series([5, 2], index=["pen", "bag"])\nweb = pd.Series([4, 3], index=["mug", "pen"])\n# Create totals with an explicit index order.\n',
        'import pandas as pd\nshop = pd.Series([5, 2], index=["pen", "bag"])\nweb = pd.Series([4, 3], index=["mug", "pen"])\ntotals = shop.add(web, fill_value=0).reindex(["pen", "bag", "mug"])',
        'assert isinstance(totals, pd.Series), "Keep labels on the result."\nassert totals.index.tolist() == ["pen", "bag", "mug"], "Use the requested order."\nassert totals.tolist() == [8, 2, 4], "Align product labels and fill absent contributions with zero."',
        'The pen entries combine, while bag and mug keep their single-channel contributions.',
        'Use .add(..., fill_value=0), then .reindex(...).',
      ),
    ],
    [
      [
        'How does pandas arithmetic pair Series entries?',
        'It aligns index labels, even when the Series have different orders.',
      ],
      [
        'What does Series.reindex(labels) do?',
        'Reorders to the requested labels and inserts missing values for absent labels.',
      ],
    ],
  ),

  skill(
    'da-table-filtering',
    'da-pandas',
    'Filter observations',
    'Express multiple conditions and choose rows and columns with loc.',
    ['da-dataframes', 'da-array-indexing', 'boolean-logic'],
    [
      'A column comparison produces a boolean Series with the same index as the table. table.loc[mask, ["name", "score"]] uses that mask to select rows and then selects the named columns. The result keeps the labels of its selected observations.',
      'Combine Series conditions with & for and, | for or, and ~ for not. Parenthesize every comparison: (table["score"] >= 80) & (table["active"] == True). Python\'s scalar and/or operators do not combine entire Series.',
      'To update a subset, use one explicit selection such as table.loc[mask, "flag"] = "review". Avoid chained assignments like table[mask]["flag"] = ...: they do not reliably update the original table and are incompatible with modern pandas copy-on-write behavior.',
    ],
    'import pandas as pd\nitems = pd.DataFrame({"name": ["pen", "bag", "mug"], "price": [2, 12, 7], "stock": [8, 0, 3]})\nmask = (items["price"] < 10) & (items["stock"] > 0)\nprint(items.loc[mask, "name"].tolist())',
    "['pen', 'mug']",
    'Each row must satisfy both conditions; the middle row fails both.',
    [
      choice(
        'Which operator combines two boolean Series using logical and?',
        ['and', '&', '&&', '+'],
        1,
        'Use element-wise & with parenthesized conditions.',
        'A Series contains many truth values.',
      ),
      choice(
        'Which selection returns named columns only for True rows in mask?',
        [
          'table.loc[mask, ["a", "b"]]',
          'table.iloc["a", "b"]',
          'table["mask", "a"]',
          'table.shape[mask]',
        ],
        0,
        'loc accepts a row mask and a list of column labels.',
        'The two loc selectors describe rows, then columns.',
      ),
      choice(
        'Which update explicitly changes the original table in one selection?',
        [
          'table[mask]["flag"] = 1',
          'table.loc[mask, "flag"] = 1',
          'table.head()["flag"] = 1',
          'table.columns = 1',
        ],
        1,
        'A single loc assignment clearly identifies the original table cells to update.',
        'Avoid selecting an intermediate table before assigning.',
      ),
      exercise(
        'Select products costing at most 10 with positive stock. Store a DataFrame eligible containing only name and price, keeping the source order.',
        'import pandas as pd\nproducts = pd.DataFrame({"name": ["clip", "desk", "cup", "pad"], "price": [3, 80, 8, 5], "stock": [4, 2, 0, 7]})\n# Create eligible.\n',
        'import pandas as pd\nproducts = pd.DataFrame({"name": ["clip", "desk", "cup", "pad"], "price": [3, 80, 8, 5], "stock": [4, 2, 0, 7]})\nmask = (products["price"] <= 10) & (products["stock"] > 0)\neligible = products.loc[mask, ["name", "price"]]',
        'assert isinstance(eligible, pd.DataFrame), "Return a table."\nassert eligible.to_dict("list") == {"name": ["clip", "pad"], "price": [3, 5]}, "Apply both conditions and select the two requested columns."\nassert len(products) == 4, "Preserve the source rows."',
        'Filtering checks each observation independently while column selection limits the resulting variables.',
        'Parenthesize the two comparisons, combine with &, and pass the mask to .loc.',
      ),
    ],
    [
      [
        'How do you combine multiple pandas row conditions?',
        'Use & or | between parenthesized comparisons; ~ negates a boolean mask.',
      ],
      [
        'How do you update selected cells in a DataFrame safely?',
        'Use one selection: table.loc[row_mask, "column"] = value.',
      ],
    ],
  ),

  skill(
    'da-csv',
    'da-cleaning',
    'Read a CSV dataset',
    'Parse delimited text from a file-like object and inspect its structure.',
    ['da-dataframes'],
    [
      'CSV stores tabular data as text: one header row names columns, and subsequent rows hold values separated by a delimiter. pd.read_csv(...) parses this representation into a DataFrame. The parser handles quoted fields, which a naive split(",") does not.',
      'These exercises use io.StringIO to wrap an embedded string as a file-like object. This makes the dataset self-contained and repeatable. With a local Python installation, read_csv can also read a file path; the table operations are the same.',
      'Set important parsing rules explicitly: sep for a delimiter, dtype for identifiers, and na_values for missing markers. A code like 007 is an identifier rather than a quantity; dtype={"code": "string"} preserves its leading zeros. Inspect columns, shape, and a small preview after loading.',
    ],
    'from io import StringIO\nimport pandas as pd\ntext = "code,quantity\\n007,4\\n012,6\\n"\norders = pd.read_csv(StringIO(text), dtype={"code": "string"})\nprint(orders["code"].tolist())\nprint(orders["quantity"].sum())',
    "['007', '012']\n10",
    'Explicit string parsing keeps identifier formatting, while quantity remains numeric.',
    [
      choice(
        'Why use a CSV parser instead of splitting each line on commas?',
        [
          'To ignore headers',
          'To handle quoting and delimiters correctly',
          'To sort every value',
          'To guarantee clean measurements',
        ],
        1,
        'A quoted field can contain a comma; a real parser knows where the field ends.',
        'A comma may be part of a quoted value.',
      ),
      choice(
        'A customer code is 004. Which dtype preserves its identity?',
        ['int', 'float', 'string', 'bool'],
        2,
        'String parsing preserves leading zeros that numeric parsing would discard.',
        'An identifier is not a number to calculate with.',
      ),
      choice(
        'What does StringIO provide to read_csv?',
        [
          'An in-memory file-like text object',
          'A database connection',
          'A random array',
          'A list of missing markers',
        ],
        0,
        'StringIO gives a string a file-reading interface without using an external file.',
        'The dataset can stay embedded in the exercise.',
      ),
      exercise(
        'Read the semicolon-separated text into events. Preserve code as a string, and store the sum of count in total.',
        'from io import StringIO\nimport pandas as pd\ntext = "code;count\\n003;5\\n009;8\\n"\n# Create events and total.\n',
        'from io import StringIO\nimport pandas as pd\ntext = "code;count\\n003;5\\n009;8\\n"\nevents = pd.read_csv(StringIO(text), sep=";", dtype={"code": "string"})\ntotal = events["count"].sum()',
        'assert isinstance(events, pd.DataFrame) and events.shape == (2, 2), "Parse two columns and two rows."\nassert events["code"].tolist() == ["003", "009"], "Preserve identifier zeros."\nassert events["count"].tolist() == [5, 8], "Parse numeric counts."\nassert total == 13, "Sum the count column."',
        'The separator and identifier dtype are part of the dataset contract.',
        'Call pd.read_csv(StringIO(text), sep=";", dtype={"code": "string"}).',
      ),
    ],
    [
      [
        'How can pandas read CSV text embedded in a Python string?',
        'Wrap it in io.StringIO, then pass that file-like object to pd.read_csv.',
      ],
      [
        'How do you preserve leading zeros in a CSV identifier column?',
        'Set its dtype to string in pd.read_csv, for example dtype={"code": "string"}.',
      ],
    ],
  ),

  skill(
    'da-missing-values',
    'da-cleaning',
    'Make missingness explicit',
    'Detect absent values and choose a justified removal or filling rule.',
    ['da-dataframes'],
    [
      "Missing values describe unavailable information. pandas can represent them with NaN, None, or a nullable dtype's pd.NA. Use .isna() or .notna() to detect missingness; equality against NaN is not a reliable detection rule.",
      '.dropna(subset=["score"]) removes rows lacking a required score. .fillna(value) replaces missing entries with a chosen value. These operations return a result by default: store it or assign the cleaned column. Count missing entries before changing them so you can explain the effect.',
      'A filling rule changes the interpretation of the dataset. A missing quantity can mean unknown rather than zero. For this exercise, a documented source contract states that a blank count means no events; zero filling is appropriate under that specific rule. For other measurements you may need to keep, investigate, or exclude missingness.',
    ],
    'import pandas as pd\ncounts = pd.Series([4, None, 7], dtype="Float64")\nprint(counts.isna().tolist())\nprint(counts.fillna(0).tolist())\nprint(counts.dropna().tolist())',
    '[False, True, False]\n[4.0, 0.0, 7.0]\n[4.0, 7.0]',
    'Detection, filling, and removal are distinct actions with distinct effects.',
    [
      choice(
        'Which operation reliably detects missing Series values?',
        ['s == float("nan")', 's.isna()', 's == 0', 's.sort_values()'],
        1,
        'isna recognizes the missing-value representations pandas supports.',
        'Missingness has a dedicated predicate.',
      ),
      choice(
        'A blank sensor measurement means unknown. What does replacing it with zero do?',
        [
          'Proves the sensor measured zero',
          'Changes unknown into an assumed zero',
          'Preserves the original information exactly',
          'Fixes all sampling bias',
        ],
        1,
        'Zero filling introduces a value that was not observed.',
        'Distinguish an absent reading from a measured zero.',
      ),
      choice(
        'How can you drop rows only when the score column is missing?',
        [
          'table.dropna(subset=["score"])',
          'table.fillna("score")',
          'table.drop("score")',
          'table.isna("score")',
        ],
        0,
        'subset limits the missingness rule to required columns.',
        'Other optional columns can remain missing.',
      ),
      exercise(
        'The source contract says a blank events value means zero events. Create cleaned with that column filled with zero and keep other values unchanged. Store the original missing count in missing_count.',
        'import pandas as pd\nraw = pd.DataFrame({"site": ["A", "B", "C"], "events": [3.0, None, 8.0]})\n# Create missing_count and cleaned without changing raw.\n',
        'import pandas as pd\nraw = pd.DataFrame({"site": ["A", "B", "C"], "events": [3.0, None, 8.0]})\nmissing_count = raw["events"].isna().sum()\ncleaned = raw.copy()\ncleaned["events"] = cleaned["events"].fillna(0)',
        'assert missing_count == 1, "Count missing entries before cleaning."\nassert cleaned["events"].tolist() == [3.0, 0.0, 8.0], "Apply the documented zero rule."\nassert cleaned["site"].tolist() == ["A", "B", "C"], "Keep site identities."\nassert raw["events"].isna().sum() == 1, "Keep the raw evidence unchanged."',
        'Preserving raw data lets you audit both the missing count and the chosen replacement rule.',
        'Count .isna(), copy the table, then assign a filled events column.',
      ),
    ],
    [
      [
        'How do you test pandas values for missingness?',
        'Use .isna() or .notna(), rather than equality with NaN.',
      ],
      [
        'Why document a missing-value filling rule?',
        'Filling replaces unavailable information with an assumption that can change the analysis.',
      ],
    ],
  ),

  skill(
    'da-conversion',
    'da-cleaning',
    'Validate numeric columns',
    'Convert text into numbers while exposing invalid inputs.',
    ['da-missing-values', 'da-table-filtering'],
    [
      'A column may look numeric while containing text, such as "12" or "unknown". pd.to_numeric(series, errors="coerce") converts valid numbers and marks invalid tokens as missing. errors="raise" instead stops at invalid input, which is useful when your schema promises all values are valid.',
      'Measure the conversion failures rather than silently discarding them. If the raw column is not missing but the converted result is missing, conversion rejected an input. This differs from a field that was already absent.',
      'Use .astype(...) when values already satisfy a known representation. pandas\' nullable "Int64" dtype, with a capital I, can store integer values together with missing entries. An ordinary NumPy integer dtype cannot represent missing values in the same way. Do not truncate decimal measurements merely to obtain integers.',
    ],
    'import pandas as pd\nraw = pd.Series(["12", "bad", "7"])\nnumbers = pd.to_numeric(raw, errors="coerce")\nprint(numbers.fillna(-1).tolist())\nprint(int(numbers.isna().sum()))',
    '[12.0, -1.0, 7.0]\n1',
    'The temporary -1 display makes the rejected token visible; it is not a cleaning recommendation.',
    [
      choice(
        'What does errors="coerce" do when to_numeric encounters "bad"?',
        [
          'Changes it to zero',
          'Treats it as one',
          'Marks it missing',
          'Keeps it as valid numeric text',
        ],
        2,
        'Invalid numeric text becomes a missing value.',
        'Coercion does not invent a numeric observation.',
      ),
      choice(
        'Which pandas dtype can hold integer counts and missing values?',
        ['"Int64"', '"int64" only', '"floatless"', '"missingint"'],
        0,
        'The nullable Int64 extension dtype supports missing integer values.',
        'Capitalization matters for this dtype name.',
      ),
      choice(
        'You expect every token to be numeric and want invalid input to stop the pipeline. Which setting fits?',
        ['errors="coerce"', 'errors="raise"', 'errors="hide"', 'fill_value=0'],
        1,
        'errors="raise" makes a violated numeric contract visible as an error.',
        'Choose strict validation, not silent missing values.',
      ),
      exercise(
        'Convert raw counts to numeric values with invalid tokens made missing, then store them using nullable Int64 in counts. Store the number of newly invalid inputs in invalid_count.',
        'import pandas as pd\nraw = pd.Series(["4", "oops", None, "9"], dtype="string")\n# Create counts and invalid_count.\n',
        'import pandas as pd\nraw = pd.Series(["4", "oops", None, "9"], dtype="string")\nconverted = pd.to_numeric(raw, errors="coerce")\ninvalid_count = (raw.notna() & converted.isna()).sum()\ncounts = converted.astype("Int64")',
        'assert isinstance(counts, pd.Series) and str(counts.dtype) == "Int64", "Use nullable integers."\nassert counts.dropna().tolist() == [4, 9], "Keep the valid counts."\nassert counts.isna().tolist() == [False, True, True, False], "Keep absent and invalid entries missing."\nassert invalid_count == 1, "Count only newly rejected nonmissing inputs."',
        'Only oops is newly invalid; the original None was already missing.',
        'Combine raw.notna() with converted.isna(), then convert to "Int64".',
      ),
    ],
    [
      [
        'What is the difference between to_numeric errors="raise" and errors="coerce"?',
        'raise rejects invalid input with an error; coerce replaces invalid numeric tokens with missing values.',
      ],
      [
        'How can you distinguish a failed conversion from an already missing input?',
        'A newly failed input is raw.notna() & converted.isna().',
      ],
    ],
  ),

  skill(
    'da-duplicates',
    'da-cleaning',
    'Define unique observations',
    'Choose a key and make a duplicate-resolution policy explicit.',
    ['da-dataframes'],
    [
      'Duplicate rows depend on the question: two identical full rows are one kind of duplicate, while two rows with the same event_id may disagree on other fields. .duplicated(subset=["event_id"]) checks the chosen key rather than every column.',
      '.drop_duplicates(subset=["event_id"], keep="first") keeps the first occurrence of each key; keep="last" keeps the last. Sorting by a trusted version or timestamp before deduplication can make that choice meaningful. Input order alone does not prove which observation is correct.',
      'Validate the key after cleaning with table["event_id"].is_unique, and record how many rows were removed. Deduplication avoids counting an event twice, but conflicting records may require investigation rather than automatic removal. A missing identifier also requires a separate policy.',
    ],
    'import pandas as pd\nrecords = pd.DataFrame({"id": [1, 2, 1], "version": [1, 1, 2], "count": [4, 5, 6]})\nlatest = records.sort_values("version").drop_duplicates("id", keep="last").sort_values("id")\nprint(latest["count"].tolist())\nprint(latest["id"].is_unique)',
    '[6, 5]\nTrue',
    'The higher version of id 1 is retained under an explicit latest-version policy.',
    [
      choice(
        'Two rows share event_id but have different counts. Which subset finds the repeated event identity?',
        [
          '["count"]',
          '["event_id"]',
          'Every column, necessarily',
          'No subset can detect it',
        ],
        1,
        'The event identifier defines the intended observation key.',
        'Duplicates are relative to a chosen identity.',
      ),
      choice(
        'What does keep="last" mean in drop_duplicates?',
        [
          'Keep the largest numeric value',
          'Keep the last row in the current order for each key',
          'Keep all repeated rows',
          'Keep only missing values',
        ],
        1,
        'It uses current row order, so order must encode your policy.',
        'The method does not infer a timestamp policy.',
      ),
      choice(
        'Which check confirms that every id value appears once after cleaning?',
        [
          'table["id"].is_unique',
          'table.shape[1] == 1',
          'table["id"].sum()',
          'table.head()',
        ],
        0,
        'is_unique checks whether the column has repeated values.',
        'Validate the key directly.',
      ),
      exercise(
        'For each id, retain the greatest version. Create latest ordered by id, then store how many source rows were removed in removed.',
        'import pandas as pd\nrecords = pd.DataFrame({"id": [2, 1, 2, 3], "version": [1, 1, 2, 1], "value": [5, 8, 9, 4]})\n# Create latest and removed.\n',
        'import pandas as pd\nrecords = pd.DataFrame({"id": [2, 1, 2, 3], "version": [1, 1, 2, 1], "value": [5, 8, 9, 4]})\nlatest = records.sort_values("version").drop_duplicates(subset=["id"], keep="last").sort_values("id")\nremoved = len(records) - len(latest)',
        'assert latest["id"].tolist() == [1, 2, 3], "Order the unique keys."\nassert latest["value"].tolist() == [8, 9, 4], "Keep the greatest version of each id."\nassert latest["id"].is_unique and removed == 1, "Validate uniqueness and count removed rows."\nassert len(records) == 4, "Keep the source table unchanged."',
        'Version sorting supplies the meaning of last; deduplication then implements the policy.',
        'Sort version ascending, keep the last duplicate id, then sort id.',
      ),
    ],
    [
      [
        'How do you define duplicates by an observation key in pandas?',
        'Use duplicated or drop_duplicates with subset=["key_column"].',
      ],
      [
        'Why sort before drop_duplicates(..., keep="last")?',
        'Last refers to current row order; sorting a trusted version or timestamp makes the selection policy meaningful.',
      ],
    ],
  ),

  skill(
    'da-text',
    'da-wrangling',
    'Normalize text keys',
    'Apply vectorized string cleaning without confusing formatting with meaning.',
    ['da-missing-values', 'string-methods'],
    [
      'Text identifiers often differ only because of surrounding whitespace or letter case. A string Series exposes vectorized methods through .str: .str.strip() removes surrounding whitespace, and .str.lower() converts letters to lowercase.',
      'Cleaning an identifier is a modeling decision. Treating "North" and "north" as the same site is reasonable only if your source contract says case is irrelevant. Preserve the original text separately when you need an audit trail.',
      '.str.contains(pattern, regex=False, na=False) performs a literal substring check, returning False for missing text. Its default pattern interpretation is regular expressions; set regex=False for a literal search, such as a dot in a product code. Choosing a missing-value rule prevents an incomplete mask.',
    ],
    'import pandas as pd\nlabels = pd.Series([" North ", "SOUTH", None], dtype="string")\nclean = labels.str.strip().str.lower()\nprint(clean.fillna("missing").tolist())\nprint(clean.str.contains("north", regex=False, na=False).tolist())',
    "['north', 'south', 'missing']\n[True, False, False]",
    'The operations clean formatting while preserving the missing entry until the display step.',
    [
      choice(
        'Which expression removes surrounding spaces and lowercases a string Series?',
        [
          's.strip().lower()',
          's.str.strip().str.lower()',
          's.astype(int)',
          's.str.sum()',
        ],
        1,
        'The .str accessor applies string methods to each nonmissing element.',
        'Use vectorized methods at both stages.',
      ),
      choice(
        'You want to search for a literal dot. Which contains setting avoids regular-expression interpretation?',
        ['regex=False', 'regex=True', 'na=True', 'axis=1'],
        0,
        'regex=False treats the pattern as literal text.',
        'A dot has special meaning in a regular expression.',
      ),
      choice(
        'Why keep the original text when normalizing identifiers?',
        [
          'To make every row unique',
          'To audit whether normalization merged distinct source values',
          'To remove missingness automatically',
          'To guarantee all matches are correct',
        ],
        1,
        'Normalization can collapse different source values, so the original is evidence for reviewing that choice.',
        'Case rules depend on the source contract.',
      ),
      exercise(
        'The site contract ignores case and surrounding spaces. Create normalized using those rules. Create is_north selecting literal north anywhere in the normalized text, with missing values treated as False.',
        'import pandas as pd\nraw = pd.Series([" NORTH ", "South", None, "north-east"], dtype="string")\n# Create normalized and is_north.\n',
        'import pandas as pd\nraw = pd.Series([" NORTH ", "South", None, "north-east"], dtype="string")\nnormalized = raw.str.strip().str.lower()\nis_north = normalized.str.contains("north", regex=False, na=False)',
        'assert normalized.fillna("MISSING").tolist() == ["north", "south", "MISSING", "north-east"], "Normalize case and spaces while preserving missingness."\nassert is_north.tolist() == [True, False, False, True], "Search literal text and define the missing rule."\nassert raw.iloc[0] == " NORTH ", "Preserve the raw text."',
        'String methods express the source normalization contract and build a complete boolean mask.',
        'Chain .str.strip() and .str.lower(); then call .str.contains(..., regex=False, na=False).',
      ),
    ],
    [
      [
        'How do you normalize a string Series for surrounding spaces and lowercase?',
        'series.str.strip().str.lower().',
      ],
      [
        'Why set regex=False and na=False for a literal substring filter?',
        'regex=False treats the pattern literally; na=False gives missing text a False mask value.',
      ],
    ],
  ),

  skill(
    'da-categories',
    'da-wrangling',
    'Represent category meaning',
    'Distinguish labels, category order, and binary indicator columns.',
    ['da-missing-values'],
    [
      'A categorical variable takes values from a defined set, such as low, medium, high. pandas Categorical can record allowed categories and whether their order matters. Alphabetical order is not necessarily the meaningful order of a severity or size scale.',
      'An ordered categorical dtype makes sorting follow the specified category order. pd.Categorical(values, categories=["low", "medium", "high"], ordered=True) records that scale. Values outside the allowed set become missing; inspect them instead of assuming the conversion validated everything.',
      'pd.get_dummies(series, dtype=int) creates one indicator column per category, with one or zero showing membership. This encoding is useful when downstream calculations require separate category indicators. A category code such as 0, 1, 2 is an internal representation, not automatically a numerical distance.',
    ],
    'import pandas as pd\nseverity = pd.Series(pd.Categorical(["high", "low", "medium"], categories=["low", "medium", "high"], ordered=True))\nprint(severity.sort_values().tolist())\nprint(pd.get_dummies(severity, dtype=int)["high"].tolist())',
    "['low', 'medium', 'high']\n[1, 0, 0]",
    'Ordering and one-hot membership encode different aspects of a categorical variable.',
    [
      choice(
        'What determines sorting for an ordered Categorical?',
        [
          'Alphabetical order only',
          'The explicit categories order',
          'The number of letters',
          'The original row index only',
        ],
        1,
        'An ordered categorical uses its declared scale.',
        'You supply the sequence of allowed categories.',
      ),
      choice(
        'A category code is 2. What can you infer without more information?',
        [
          'It is twice category 1',
          'It is an internal identifier, not a numeric distance',
          'It is a measured quantity',
          'It is always missing',
        ],
        1,
        'Encoding identifiers does not create meaningful arithmetic distances.',
        'A code represents a label.',
      ),
      choice(
        'What does get_dummies(..., dtype=int) create?',
        [
          'One integer membership column per category',
          'A single sorted label',
          'A date index',
          'Random category names',
        ],
        0,
        'Each column flags membership with one or zero.',
        'Think of a separate yes/no question for every category.',
      ),
      exercise(
        'Create sizes as an ordered categorical Series with order small, medium, large. Store sorted_sizes as a sorted Python list and indicators as integer dummy columns.',
        'import pandas as pd\nvalues = ["large", "small", "medium", "small"]\n# Create sizes, sorted_sizes, and indicators.\n',
        'import pandas as pd\nvalues = ["large", "small", "medium", "small"]\nsizes = pd.Series(pd.Categorical(values, categories=["small", "medium", "large"], ordered=True))\nsorted_sizes = sizes.sort_values().tolist()\nindicators = pd.get_dummies(sizes, dtype=int)',
        'assert isinstance(sizes.dtype, pd.CategoricalDtype) and sizes.cat.ordered, "Declare an ordered categorical."\nassert sizes.cat.categories.tolist() == ["small", "medium", "large"], "Specify the semantic size order."\nassert sorted_sizes == ["small", "small", "medium", "large"], "Sort by category meaning."\nassert indicators["small"].tolist() == [0, 1, 0, 1] and indicators["large"].tolist() == [1, 0, 0, 0], "Build category membership indicators."',
        'A declared order represents size ranking; dummy columns represent membership per original row.',
        'Use pd.Categorical with categories and ordered=True, then pd.get_dummies(..., dtype=int).',
      ),
    ],
    [
      [
        'What does ordered=True add to a pandas Categorical?',
        'The declared categories sequence becomes a meaningful order for sorting and comparisons.',
      ],
      [
        'Are categorical codes automatically numeric measurements?',
        'No. They identify categories; their differences do not imply meaningful distances.',
      ],
    ],
  ),

  skill(
    'da-joins',
    'da-wrangling',
    'Join tables with a contract',
    'Enrich rows by key and validate the expected relationship.',
    ['da-duplicates'],
    [
      'pd.merge(left, right, on="key", how="left") adds matching right-table columns while retaining every left-table key. An inner join retains only keys found on both sides. Choosing a join type determines which observations remain in your analysis.',
      'A left join can still increase the row count when the right table contains repeated matching keys. If many events should match one site description, validate="many_to_one" checks that the right-side key is unique and raises an error if the contract is broken.',
      'indicator=True adds a _merge column showing whether each result was matched or came from only one side. Inspect unmatched rows rather than silently dropping them. pandas can match null keys with each other, so missing join identifiers require a deliberate policy before merging.',
    ],
    'import pandas as pd\nevents = pd.DataFrame({"site": ["A", "B", "A"], "count": [2, 5, 3]})\nsites = pd.DataFrame({"site": ["A", "B"], "region": ["east", "west"]})\njoined = events.merge(sites, on="site", how="left", validate="many_to_one")\nprint(joined["region"].tolist())\nprint(len(joined))',
    "['east', 'west', 'east']\n3",
    'Repeated event keys are expected, but each site has exactly one region description.',
    [
      choice(
        'Which join keeps every left-side observation key, including unmatched ones?',
        ['inner', 'left', 'cross', 'None'],
        1,
        'A left join retains left observations and places missing values in unmatched right columns.',
        'Name the side whose observations you preserve.',
      ),
      choice(
        'Why can a left join produce more rows than its left input?',
        [
          'All left joins delete the index',
          'Repeated matching right keys create multiple matches',
          'Strings cannot be joined',
          'validate always duplicates rows',
        ],
        1,
        'Each matching pair becomes a row, so repeated right-side keys can multiply observations.',
        'Preserving left keys does not imply preserving exactly one row per key.',
      ),
      choice(
        'Many orders should reference one product description. Which validation fits?',
        ['many_to_many', 'one_to_many', 'many_to_one', 'none_to_one'],
        2,
        'The left has many orders per product, and the right must have one description per product.',
        'Read the relationship from left input to right input.',
      ),
      exercise(
        'Enrich events with region using a left many-to-one join on site. Keep unmatched site C and include an indicator. Store the number of unmatched rows in unmatched.',
        'import pandas as pd\nevents = pd.DataFrame({"site": ["A", "C", "A"], "count": [4, 2, 6]})\nsites = pd.DataFrame({"site": ["A", "B"], "region": ["east", "west"]})\n# Create enriched and unmatched.\n',
        'import pandas as pd\nevents = pd.DataFrame({"site": ["A", "C", "A"], "count": [4, 2, 6]})\nsites = pd.DataFrame({"site": ["A", "B"], "region": ["east", "west"]})\nenriched = events.merge(sites, on="site", how="left", validate="many_to_one", indicator=True)\nunmatched = (enriched["_merge"] == "left_only").sum()',
        'assert len(enriched) == 3 and enriched["site"].tolist() == ["A", "C", "A"], "Preserve all event rows in source order."\nassert enriched["region"].fillna("UNKNOWN").tolist() == ["east", "UNKNOWN", "east"], "Match known sites without inventing C data."\nassert "_merge" in enriched.columns and unmatched == 1, "Audit the unmatched event."',
        'The join enriches observations without silently losing a missing lookup key.',
        'Use .merge(..., how="left", validate="many_to_one", indicator=True).',
      ),
    ],
    [
      [
        'What does validate="many_to_one" check during a pandas merge?',
        'The right-side join keys must be unique; repeated left keys are allowed.',
      ],
      [
        'Why inspect indicator=True after a merge?',
        'Its _merge column identifies matched and unmatched rows so missing lookup coverage is visible.',
      ],
    ],
  ),

  skill(
    'da-reshape',
    'da-wrangling',
    'Change table shape',
    'Move measurements between wide columns and long rows without changing meaning.',
    ['da-duplicates'],
    [
      'A wide table has separate columns for repeated measurements, such as morning and evening. A long table has one measurement column and another variable identifying which measurement it represents. Long form often makes grouping and plotting easier.',
      '.melt(id_vars=["site"], value_vars=["morning", "evening"], var_name="period", value_name="count") keeps the site identifier while turning measurement columns into period/count rows. Each original observation contributes one row per measured period.',
      '.pivot(index="site", columns="period", values="count") converts long data back to a wide table when each site/period pair is unique. Repeated pairs make pivot ambiguous and cause an error. Aggregation is a separate decision; do not silently average duplicate measurements just to make a reshape succeed.',
    ],
    'import pandas as pd\nwide = pd.DataFrame({"site": ["A", "B"], "morning": [3, 5], "evening": [4, 6]})\nlong = wide.melt(id_vars=["site"], var_name="period", value_name="count")\nprint(long.shape)\nprint(long["count"].tolist())',
    '(4, 3)\n[3, 5, 4, 6]',
    'Two sites with two measured periods become four site-period observations.',
    [
      choice(
        'A wide table has five identifiers and three measurement columns. How many rows does melting those measurements produce?',
        ['5', '3', '8', '15'],
        3,
        'Each of five identifiers contributes one row per measurement: 5 × 3.',
        'Melting increases rows while reducing measurement columns.',
      ),
      choice(
        'What does id_vars specify in melt?',
        [
          'Columns that remain observation identifiers',
          'Columns to average',
          'Random row numbers',
          'Allowed data types only',
        ],
        0,
        'Identifier columns are repeated as measurement columns become long rows.',
        'Which information should stay attached to every measurement?',
      ),
      choice(
        'Why does pivot fail when the same index/column pair appears twice?',
        [
          'Long tables cannot be reshaped',
          'There is no single value for the target cell',
          'It requires CSV input',
          'The labels must be numbers',
        ],
        1,
        'Multiple measurements compete for the same output cell, requiring an explicit resolution policy.',
        'One wide cell needs one value.',
      ),
      exercise(
        'Melt morning and evening measurements into a table long with columns site, period, count. Then pivot it back into restored, using site as index and period as columns.',
        'import pandas as pd\nwide = pd.DataFrame({"site": ["A", "B"], "morning": [2, 7], "evening": [5, 9]})\n# Create long and restored.\n',
        'import pandas as pd\nwide = pd.DataFrame({"site": ["A", "B"], "morning": [2, 7], "evening": [5, 9]})\nlong = wide.melt(id_vars=["site"], value_vars=["morning", "evening"], var_name="period", value_name="count")\nrestored = long.pivot(index="site", columns="period", values="count")',
        'assert long.columns.tolist() == ["site", "period", "count"] and len(long) == 4, "Keep identifiers and create measurement rows."\nassert set(zip(long["site"], long["period"], long["count"])) == {("A", "morning", 2), ("B", "morning", 7), ("A", "evening", 5), ("B", "evening", 9)}, "Preserve each measurement."\nassert restored.loc["A", "morning"] == 2 and restored.loc["B", "evening"] == 9, "Restore the wide table by unique site-period pairs."',
        'Reshaping changes the organization of observations without changing their measured values.',
        'Use .melt(...) and then .pivot(index="site", columns="period", values="count").',
      ),
    ],
    [
      [
        'What is the difference between wide and long measurement tables?',
        'Wide uses one column per repeated measurement; long uses a measurement-name column and a value column.',
      ],
      [
        'What uniqueness rule does DataFrame.pivot require?',
        'Each combination of output index and column labels must identify at most one value.',
      ],
    ],
  ),

  skill(
    'da-groupby',
    'da-grouping',
    'Summarize by group',
    'Separate group keys from measured values and reduce each group.',
    ['da-missing-values'],
    [
      'groupby partitions observations by a key, then lets you calculate a result for each group. table.groupby("site")["count"].sum() sums counts for each site. The grouping object describes groups; a reduction such as sum or mean actually computes the summary.',
      'The key identifies groups and the selected numeric column supplies measurements. By default, a grouping key containing missing values is excluded. Use dropna=False when missing-key observations should form a visible group, and explain what that group represents.',
      'Grouping reduces the number of observations. A grouped mean weights each row equally, so consider whether rows represent equally important units. For a simple total, sum measures the combined contribution; count counts nonmissing values, while size counts rows regardless of missing measurements.',
    ],
    'import pandas as pd\nvisits = pd.DataFrame({"site": ["A", "B", "A", "B"], "count": [3, 4, 5, 2]})\ntotals = visits.groupby("site")["count"].sum()\nprint(totals.to_dict())',
    "{'A': 8, 'B': 6}",
    'Each site becomes one group, and its count values are added.',
    [
      choice(
        'What does df.groupby("region")["sales"].sum() return?',
        [
          'One total per region',
          'One row per sale unchanged',
          'The number of columns',
          'Only the first sale',
        ],
        0,
        'The region key partitions rows; sum reduces sales within each partition.',
        'A group reduction produces one value per group.',
      ),
      choice(
        'What is the difference between GroupBy count and size?',
        [
          'Both always count missing values',
          'count excludes missing values; size counts rows',
          'size counts columns; count counts rows',
          'count calculates an average',
        ],
        1,
        'count measures nonmissing observations per selected column; size measures group row count.',
        'Missing measurements can still occupy rows.',
      ),
      choice(
        'How can a missing grouping key remain visible as its own group?',
        ['dropna=False', 'dropna=True', 'fill_value=True', 'axis="missing"'],
        0,
        'dropna=False includes a missing-key group instead of excluding those rows.',
        'Make exclusion of unidentified observations explicit.',
      ),
      exercise(
        'Calculate units sold per shop from sales. Store totals as a Series with shop labels sorted alphabetically, and row_counts as the number of rows per shop.',
        'import pandas as pd\nsales = pd.DataFrame({"shop": ["west", "east", "west", "east", "west"], "units": [2, 4, 5, 1, 3]})\n# Create totals and row_counts.\n',
        'import pandas as pd\nsales = pd.DataFrame({"shop": ["west", "east", "west", "east", "west"], "units": [2, 4, 5, 1, 3]})\ntotals = sales.groupby("shop")["units"].sum().sort_index()\nrow_counts = sales.groupby("shop").size().sort_index()',
        'assert isinstance(totals, pd.Series) and totals.to_dict() == {"east": 5, "west": 10}, "Sum units within each shop."\nassert totals.index.tolist() == ["east", "west"], "Use the requested group order."\nassert row_counts.to_dict() == {"east": 2, "west": 3}, "Count group rows."',
        'A grouped sum and grouped size answer different questions about the same partition.',
        'Select units before .sum(); use .size() for row counts.',
      ),
    ],
    [
      [
        'What does groupby(key)[value].sum() calculate?',
        'It adds the value column within each group defined by the key.',
      ],
      [
        'How do GroupBy.size() and GroupBy.count() differ?',
        'size counts group rows; count counts nonmissing values in each selected column.',
      ],
    ],
  ),

  skill(
    'da-aggregations',
    'da-grouping',
    'Name summary measures',
    'Build a compact table containing multiple explicit group statistics.',
    ['da-groupby'],
    [
      'A useful grouped summary often needs several measures, such as revenue total and observation count. Named aggregation makes the output contract readable: table.groupby("shop").agg(total=("revenue", "sum"), records=("revenue", "size")). Each output name maps to an input column and reduction.',
      'Choose statistics based on their meaning, not habit. mean is sensitive to extreme values; median describes the middle value. A sum measures total activity and can hide differences in group size, so include counts when comparing groups.',
      "Set as_index=False when group keys should remain ordinary columns instead of becoming the result index. This often makes the summary easier to join or export. sort_values then orders observations by a chosen measure, rather than changing the groups' meaning.",
    ],
    'import pandas as pd\norders = pd.DataFrame({"shop": ["A", "A", "B"], "amount": [10, 30, 25]})\nsummary = orders.groupby("shop", as_index=False).agg(total=("amount", "sum"), average=("amount", "mean"), orders=("amount", "size"))\nprint(summary.to_dict("list"))',
    "{'shop': ['A', 'B'], 'total': [40, 25], 'average': [20.0, 25.0], 'orders': [2, 1]}",
    'Explicitly named columns distinguish the total, average, and number of source rows.',
    [
      choice(
        'In agg(total=("amount", "sum")), what does total name?',
        [
          'The input column',
          'The output column',
          'The grouping key',
          'A missing marker',
        ],
        1,
        'The keyword total is the resulting summary column name.',
        'The tuple names the source and operation.',
      ),
      choice(
        'Why compare group means together with group counts?',
        [
          'Counts prove causation',
          'A mean alone hides how many observations support it',
          'Counts remove all outliers',
          'Every group must have equal counts',
        ],
        1,
        'A mean based on one row has different support from a mean based on hundreds.',
        'A summary value does not reveal its sample size.',
      ),
      choice(
        'What does as_index=False do in a grouped aggregation?',
        [
          'Keeps grouping keys as ordinary columns',
          'Removes every grouping key',
          'Makes the result a list',
          'Disables grouping',
        ],
        0,
        'Group labels remain available as columns for export or joins.',
        'The result can stay a regular observation table.',
      ),
      exercise(
        'Build summary with columns team, total, average, and records. Group by team, sum and average points, and count rows. Sort teams alphabetically.',
        'import pandas as pd\nscores = pd.DataFrame({"team": ["B", "A", "B", "A"], "points": [8, 3, 12, 7]})\n# Create summary using named aggregation.\n',
        'import pandas as pd\nscores = pd.DataFrame({"team": ["B", "A", "B", "A"], "points": [8, 3, 12, 7]})\nsummary = scores.groupby("team", as_index=False).agg(total=("points", "sum"), average=("points", "mean"), records=("points", "size")).sort_values("team")',
        'assert isinstance(summary, pd.DataFrame), "Create a summary table."\nassert summary.to_dict("list") == {"team": ["A", "B"], "total": [10, 20], "average": [5.0, 10.0], "records": [2, 2]}, "Name and calculate the requested group measures."',
        'Named aggregation records exactly which source column and operation produced each result.',
        'Use .agg(total=("points", "sum"), average=("points", "mean"), records=("points", "size")).',
      ),
    ],
    [
      [
        'How do you write a named pandas aggregation?',
        'groupby(...).agg(output_name=("input_column", "operation")).',
      ],
      [
        'What does groupby(..., as_index=False) preserve in an aggregate table?',
        'Grouping keys remain ordinary result columns.',
      ],
    ],
  ),

  skill(
    'da-transforms',
    'da-grouping',
    'Keep row-level context',
    'Attach group summaries to each observation with transform.',
    ['da-groupby', 'da-label-alignment'],
    [
      'An aggregation creates a reduced summary with one row per group. transform instead returns a value for each original observation. table.groupby("team")["score"].transform("mean") repeats each team\'s mean on the rows belonging to that team.',
      'This matching shape lets you compute deviations, shares, and within-group comparisons without a separate merge. A group-centered value is original minus group mean. A contribution share is original divided by group total, provided that total is nonzero.',
      "Transformation preserves observation-level detail but changes the interpretation of a variable. A positive centered score means above that group's mean, not necessarily above the global mean. Check missing values and zero denominators before using a normalized measure in a report.",
    ],
    'import pandas as pd\nscores = pd.DataFrame({"team": ["A", "A", "B"], "score": [2, 6, 10]})\nmeans = scores.groupby("team")["score"].transform("mean")\nprint(means.tolist())\nprint((scores["score"] - means).tolist())',
    '[4.0, 4.0, 10.0]\n[-2.0, 2.0, 0.0]',
    'Each observation keeps its row while gaining the context of its own group.',
    [
      choice(
        'How many values does a group transform normally return?',
        [
          'One per group only',
          'One per original row',
          'One for the whole table',
          'One per column name',
        ],
        1,
        'Transform broadcasts each group result back to its original rows.',
        'It is designed for aligned row-level calculations.',
      ),
      choice(
        'A centered score is value minus group mean. What does a positive result mean?',
        [
          "Above that group's mean",
          "Above every other group's values",
          'The group total is positive',
          'The score was missing',
        ],
        0,
        "The reference is the observation's own group average.",
        'Name the reference population.',
      ),
      choice(
        "Before computing each row's share of its group total, what condition matters?",
        [
          'The group total is nonzero',
          'Every label is uppercase',
          'The table has no index',
          'The sum must equal the mean',
        ],
        0,
        'A zero denominator makes a ratio undefined, so it needs an explicit policy.',
        'A share is a division.',
      ),
      exercise(
        "Compute each row's team mean as means and its deviation from that mean as centered. Keep the original row order.",
        'import pandas as pd\ndata = pd.DataFrame({"team": ["A", "B", "A", "B"], "value": [4, 10, 8, 14]})\n# Create means and centered as Series.\n',
        'import pandas as pd\ndata = pd.DataFrame({"team": ["A", "B", "A", "B"], "value": [4, 10, 8, 14]})\nmeans = data.groupby("team")["value"].transform("mean")\ncentered = data["value"] - means',
        'assert isinstance(means, pd.Series) and means.tolist() == [6.0, 12.0, 6.0, 12.0], "Repeat each group mean at its original rows."\nassert isinstance(centered, pd.Series) and centered.tolist() == [-2.0, -2.0, 2.0, 2.0], "Subtract the corresponding team mean."\nassert centered.index.equals(data.index), "Preserve observation alignment."',
        'Transform attaches the correct reference value to every row before subtraction.',
        'Use .transform("mean") instead of .mean() so the result matches the original table.',
      ),
    ],
    [
      [
        'How does pandas transform differ from aggregation?',
        'Aggregation reduces to group summaries; transform returns a value aligned to each original row.',
      ],
      [
        'How do you center a value within its group?',
        'Subtract groupby(key)[value].transform("mean") from the original value column.',
      ],
    ],
  ),

  skill(
    'da-window',
    'da-grouping',
    'Calculate moving summaries',
    'Use ordered rolling windows and understand incomplete leading windows.',
    ['da-missing-values'],
    [
      'A rolling calculation summarizes a moving neighborhood of observations. values.rolling(window=3).mean() averages the current value and two preceding values in row order. Unlike a group summary, it can produce a different local reference for every row.',
      'The default min_periods for a fixed-size window requires a full window, so the first two results of a three-row mean are missing. min_periods=1 permits a result from fewer observations; that changes the amount of evidence supporting early results.',
      'Sort observations by their meaningful order before applying a rolling window. Three rows are not necessarily three days when observations are irregular. centered windows can use future observations, so a predictive feature should use only information available at the prediction time.',
    ],
    'import pandas as pd\nvalues = pd.Series([2, 4, 9, 7])\nprint(values.rolling(2, min_periods=1).mean().tolist())\nprint(values.rolling(2).mean().fillna(-1).tolist())',
    '[2.0, 3.0, 6.5, 8.0]\n[-1.0, 3.0, 6.5, 8.0]',
    'The first full two-row window appears at position one; allowing one observation fills the leading result.',
    [
      choice(
        'What does rolling(3).mean() use at a row after a full window exists?',
        [
          'The next three rows',
          'The current and preceding two rows',
          'Every row in the dataset',
          'Only rows equal to the current value',
        ],
        1,
        'The default trailing window uses current and previous observations.',
        'The default is not centered.',
      ),
      choice(
        'Why are leading results missing for rolling(3) by default?',
        [
          'The values must be strings',
          'A complete three-observation window is not yet available',
          'All rolling windows delete early rows',
          'The index starts at zero',
        ],
        1,
        'The default min_periods requires three observations for the result.',
        'Count how many observations exist at the first row.',
      ),
      choice(
        'Why sort timestamps before a rolling analysis?',
        [
          'Rolling respects row order, which must match time order',
          'Sorting removes every missing value',
          'A mean requires alphabetical order',
          'Timestamps cannot be indices',
        ],
        0,
        'An unsorted table gives a neighborhood that does not represent consecutive time observations.',
        'The window follows the order of the supplied rows.',
      ),
      exercise(
        'Compute a trailing three-observation mean for values, requiring all three observations. Store it as moving. Keep the first two results missing.',
        'import pandas as pd\nvalues = pd.Series([3, 6, 9, 12, 15])\n# Create moving.\n',
        'import pandas as pd\nvalues = pd.Series([3, 6, 9, 12, 15])\nmoving = values.rolling(window=3).mean()',
        'assert isinstance(moving, pd.Series) and len(moving) == 5, "Keep a result aligned to every row."\nassert moving.isna().tolist() == [True, True, False, False, False], "Require three observations per window."\nassert moving.dropna().tolist() == [6.0, 9.0, 12.0], "Average each trailing triple."',
        'A complete trailing window produces the mean of [3,6,9], then [6,9,12], then [9,12,15].',
        'Call values.rolling(window=3).mean() with the default minimum count.',
      ),
    ],
    [
      [
        'What does a default fixed-size pandas rolling window contain?',
        'The current row and preceding rows up to the window size; the default requires a full window.',
      ],
      [
        'Why distinguish a three-row window from a three-day window?',
        'Irregular observations mean a fixed number of rows can span different amounts of time.',
      ],
    ],
  ),

  skill(
    'da-datetime',
    'da-analysis',
    'Parse and order timestamps',
    'Convert text into datetime values with explicit format and time-zone meaning.',
    ['da-conversion'],
    [
      'Timestamps stored as text need parsing before time calculations. pd.to_datetime(values, format="%Y-%m-%d", errors="raise") makes the expected representation explicit. Ambiguous day/month strings should use a declared format rather than relying on guesses.',
      'utc=True converts timestamps containing offsets into a shared UTC time basis. A timestamp such as 2024-01-02T00:30:00+02:00 describes the same instant as 2024-01-01T22:30:00Z. Sorting normalized timestamps sorts instants rather than their original text.',
      'Time-zone-naive values have no declared offset. Passing utc=True treats naive inputs as UTC; it does not discover their original local zone. Local business dates may differ from UTC dates, so choose the reporting zone before extracting dates with .dt.date or grouping by day.',
    ],
    'import pandas as pd\nraw = pd.Series(["2024-01-02T00:30:00+02:00", "2024-01-01T23:30:00+00:00"])\ntimes = pd.to_datetime(raw, utc=True)\nprint(times.dt.strftime("%Y-%m-%d %H:%M").tolist())',
    "['2024-01-01 22:30', '2024-01-01 23:30']",
    'Different offsets become comparable UTC instants before formatting.',
    [
      choice(
        'Why specify format when parsing strings like 03/04/2024?',
        [
          'It settles whether the first number is a day or a month',
          'It removes all invalid dates',
          'It changes every date to today',
          'It discards the year',
        ],
        0,
        'A declared format avoids ambiguous interpretations.',
        'The same text can mean two different dates.',
      ),
      choice(
        'What does utc=True do for timestamps carrying explicit offsets?',
        [
          'Keeps their displayed clock times unchanged',
          'Converts them to a shared UTC basis',
          'Deletes their time components',
          'Sorts them automatically',
        ],
        1,
        'The instant is preserved while its representation changes to UTC.',
        'Normalize offsets before comparing instants.',
      ),
      choice(
        'A naive timestamp is parsed with utc=True. What assumption was made?',
        [
          'Its actual local zone was discovered',
          'The input was treated as UTC',
          'It became missing',
          'It was treated as every zone at once',
        ],
        1,
        'Without an offset, pandas cannot infer the original zone from the text.',
        'No time-zone metadata exists in a naive value.',
      ),
      exercise(
        'Parse the ISO timestamp strings into UTC in events["time"]. Create ordered sorted by time ascending, and store the UTC hours in hours.',
        'import pandas as pd\nevents = pd.DataFrame({"id": ["late", "early"], "text": ["2024-02-01T15:00:00+00:00", "2024-02-01T10:00:00+02:00"]})\n# Create time, ordered, and hours.\n',
        'import pandas as pd\nevents = pd.DataFrame({"id": ["late", "early"], "text": ["2024-02-01T15:00:00+00:00", "2024-02-01T10:00:00+02:00"]})\nevents["time"] = pd.to_datetime(events["text"], utc=True)\nordered = events.sort_values("time")\nhours = ordered["time"].dt.hour.tolist()',
        'assert str(events["time"].dt.tz) == "UTC", "Normalize to UTC."\nassert ordered["id"].tolist() == ["early", "late"], "Sort by actual instants."\nassert hours == [8, 15], "Extract normalized UTC hours."',
        '10:00 at UTC+02 is 08:00 UTC, so it precedes the 15:00 UTC event.',
        'Use pd.to_datetime(..., utc=True), .sort_values("time"), and .dt.hour.',
      ),
    ],
    [
      [
        'Why use an explicit format when parsing ambiguous date text?',
        'It declares the intended day/month/year interpretation rather than relying on guessing.',
      ],
      [
        'Does utc=True discover the original zone of a naive timestamp?',
        'No. A naive input is treated as UTC; its actual source zone must be supplied separately.',
      ],
    ],
  ),

  skill(
    'da-resampling',
    'da-analysis',
    'Summarize time intervals',
    'Group timestamped observations into declared reporting bins.',
    ['da-datetime', 'da-groupby'],
    [
      'Resampling groups observations into time intervals. With a DatetimeIndex, series.resample("D").sum() calculates one total per calendar day. A DataFrame can use a timestamp column directly with resample("D", on="time").',
      'Frequency and aggregation are separate decisions. Daily sums answer total activity, while daily means answer average observed value. Resampling can create intervals with no observations; sum may produce zero by default, while sum(min_count=1) retains missingness when there were no measurements.',
      'The reporting time zone and interval boundaries are part of the analysis contract. Convert to the business reporting zone before forming local-day bins. A missing interval is not proof of zero activity: a pipeline outage could have prevented collection.',
    ],
    'import pandas as pd\ntimes = pd.to_datetime(["2024-01-01 08:00", "2024-01-01 18:00", "2024-01-03 09:00"])\nvalues = pd.Series([2, 5, 4], index=times)\ndaily = values.resample("D").sum(min_count=1)\nprint(daily.fillna(-1).tolist())',
    '[7.0, -1.0, 4.0]',
    'Two readings combine on January 1; January 2 remains missing because no reading was observed.',
    [
      choice(
        'Which operation produces daily totals from a datetime-indexed Series?',
        [
          's.resample("D").sum()',
          's.sort_values("D")',
          's.groupby(1).head()',
          's.astype("day")',
        ],
        0,
        'resample creates daily bins and sum reduces the observations in each bin.',
        'Define time bins first, then a reduction.',
      ),
      choice(
        'Why use sum(min_count=1) for intervals with no measurements?',
        [
          'To turn all values into one',
          'To keep empty intervals missing rather than assuming zero',
          'To remove all time zones',
          'To demand one whole month',
        ],
        1,
        'A minimum of one valid measurement avoids inventing an observed zero for an empty bin.',
        'No reading and a measured zero are different.',
      ),
      choice(
        'When reporting by local calendar day, when should you convert the timestamps to the reporting zone?',
        [
          'Before resampling into days',
          'Only after deleting timestamps',
          'It never affects daily bins',
          'After aggregating UTC days, with no change',
        ],
        0,
        'Converting first ensures midnight boundaries refer to the intended local zone.',
        'An instant can have different calendar dates in different zones.',
      ),
      exercise(
        'Create daily totals of amount by UTC day. Keep empty days missing rather than zero. Store the result as a Series daily using the time column for resampling.',
        'import pandas as pd\nrecords = pd.DataFrame({"time": pd.to_datetime(["2024-03-01T08:00Z", "2024-03-01T18:00Z", "2024-03-03T10:00Z"], utc=True), "amount": [4, 7, 9]})\n# Create daily.\n',
        'import pandas as pd\nrecords = pd.DataFrame({"time": pd.to_datetime(["2024-03-01T08:00Z", "2024-03-01T18:00Z", "2024-03-03T10:00Z"], utc=True), "amount": [4, 7, 9]})\ndaily = records.resample("D", on="time")["amount"].sum(min_count=1)',
        'assert isinstance(daily, pd.Series) and len(daily) == 3, "Produce one bin per day from March 1 through March 3."\nassert daily.index.strftime("%Y-%m-%d").tolist() == ["2024-03-01", "2024-03-02", "2024-03-03"], "Use daily timestamp bins."\nassert daily.iloc[0] == 11 and pd.isna(daily.iloc[1]) and daily.iloc[2] == 9, "Sum observed days and keep the unobserved day missing."',
        'The minimum observation count preserves the difference between no events recorded and an observed zero.',
        'Use records.resample("D", on="time")["amount"].sum(min_count=1).',
      ),
    ],
    [
      [
        'What two decisions define a pandas resampling calculation?',
        'A time-bin frequency and an aggregation, such as resample("D").sum().',
      ],
      [
        'Why use sum(min_count=1) in a resampled measurement series?',
        'It leaves empty bins missing instead of treating a lack of observations as zero.',
      ],
    ],
  ),

  skill(
    'da-exploration',
    'da-analysis',
    'Explore evidence carefully',
    'Compare descriptive statistics, unusual values, and the limits of association.',
    ['da-aggregations', 'da-categories'],
    [
      'Exploratory analysis begins with data quality and distributions. Check observation counts, missing counts, and group coverage before interpreting an average. value_counts() summarizes category frequencies; describe() provides common numerical summaries such as count, mean, minimum, quartiles, and maximum.',
      'Mean and median answer different questions when extreme values exist. For [2, 3, 4, 51], the median is 3.5 and the mean is 15. A difference between them is a reason to inspect the distribution and observations, not automatically to delete the largest value.',
      'Correlation summarizes linear association, not causation. Shared trends, selection, and confounding variables can create association. For a report, state what was measured, how many observations support it, and which assumptions remain; choose a plot that matches the variable types rather than presenting a statistic without context.',
    ],
    'import pandas as pd\nvalues = pd.Series([2, 3, 4, 51])\nprint(float(values.mean()))\nprint(float(values.median()))\nprint(values.describe()[["count", "min", "max"]].tolist())',
    '15.0\n3.5\n[4.0, 2.0, 51.0]',
    'One large measurement strongly affects the mean while the median stays near the middle observations.',
    [
      choice(
        'An extreme value makes the mean much larger than the median. What is a sound next step?',
        [
          'Delete the extreme value automatically',
          'Inspect its source and the distribution',
          'Declare the median false',
          'Hide the sample size',
        ],
        1,
        'An extreme value may be real or erroneous; inspect evidence before deciding.',
        'A statistical surprise is a question, not a deletion policy.',
      ),
      choice(
        'Two measured variables are strongly correlated. What is established by correlation alone?',
        [
          'One caused the other',
          'A linear association in the measured data',
          'No confounding exists',
          'All future values are predictable',
        ],
        1,
        'Correlation measures association without establishing a causal explanation.',
        'The statistic does not identify an intervention.',
      ),
      choice(
        'Which summary reveals the frequency of category labels?',
        ['value_counts()', 'astype(float)', 'iloc[0]', 'ndim'],
        0,
        'value_counts counts observations for each distinct label.',
        'You want a distribution over named categories.',
      ),
      exercise(
        'Create a dictionary report containing count, missing, mean, and median for measurements. Count only nonmissing observations in count, and count missing entries separately.',
        'import pandas as pd\nmeasurements = pd.Series([2.0, 3.0, None, 4.0, 51.0])\n# Create report with the four requested keys.\n',
        'import pandas as pd\nmeasurements = pd.Series([2.0, 3.0, None, 4.0, 51.0])\nreport = {"count": int(measurements.count()), "missing": int(measurements.isna().sum()), "mean": float(measurements.mean()), "median": float(measurements.median())}',
        'assert isinstance(report, dict), "Create a dictionary report."\nassert report == {"count": 4, "missing": 1, "mean": 15.0, "median": 3.5}, "Report support, missingness, and both location summaries."',
        'The report shows both data coverage and the influence of the large observation on the mean.',
        'Use count(), isna().sum(), mean(), and median() on the Series.',
      ),
    ],
    [
      [
        'Why inspect both mean and median during exploration?',
        'Their difference can reveal asymmetry or extreme values that deserve investigation.',
      ],
      [
        'What does correlation alone establish?',
        'An association in the measured data, not a causal relationship.',
      ],
    ],
  ),

  skill(
    'da-pipeline',
    'da-analysis',
    'Build a repeatable analysis',
    'Combine loading, validation, deduplication, grouping, and assertions in a function.',
    [
      'da-csv',
      'da-conversion',
      'da-duplicates',
      'da-groupby',
      'errors',
      'problem-solving',
    ],
    [
      'A repeatable pipeline expresses the analysis as a sequence of explicit transformations: parse a source, normalize types, validate assumptions, resolve duplicate observations, and calculate a report. A function makes that sequence reusable for a new input without relying on notebook state.',
      'Each stage should declare what one row means and what keys identify it. Assertions can check that an identifier is unique, required fields are present, or totals match an expected conservation rule. These checks make a changed source contract fail visibly rather than quietly changing a report.',
      'Keep data and policies separate. In this exercise, blank or invalid quantities are rejected, and the greatest version wins for each event_id. A report should preserve these choices in its documentation. The function returns a fresh result, so calling it twice with the same text produces the same answer.',
    ],
    'from io import StringIO\nimport pandas as pd\n\ndef total_events(text):\n    data = pd.read_csv(StringIO(text))\n    data["count"] = pd.to_numeric(data["count"], errors="raise")\n    assert data["id"].is_unique, "Duplicate event id"\n    return int(data["count"].sum())\n\nprint(total_events("id,count\\n1,4\\n2,7\\n"))',
    '11',
    'The function owns parsing and validation, so the result is independent of previous interactive runs.',
    [
      choice(
        'Why put an analysis pipeline in a function accepting source data?',
        [
          'To rely on hidden notebook variables',
          'To make inputs and transformations explicit and repeatable',
          'To skip validation',
          'To make every source valid',
        ],
        1,
        'An explicit input and returned result reduce dependence on unrelated interactive state.',
        'The same input should reproduce the same output.',
      ),
      choice(
        'A required event_id stops being unique. What should a validation check do?',
        [
          'Silently count duplicates twice',
          'Expose the violated contract before reporting totals',
          'Rename the output column',
          'Assume duplicate rows are always correct',
        ],
        1,
        'A key violation changes observation meaning and should be resolved before reporting.',
        'A successful-looking number can still represent invalid data.',
      ),
      choice(
        'Which item belongs in the documentation of a reproducible cleaning pipeline?',
        [
          'Only the final total',
          'The missing-value and duplicate-resolution policies',
          'A claim that all errors are impossible',
          "The author's favorite color",
        ],
        1,
        'These policies determine which observations contribute to the result.',
        'Another analyst should be able to explain the transformations.',
      ),
      exercise(
        'Write summarize(text). Parse CSV columns event_id, version, shop, units. Validate units with errors="raise" and reject missing quantities. Retain the greatest version per event_id, then return a Series of total units per shop sorted alphabetically. Repeated event ids have unique versions. Invalid or missing quantities must raise an error.',
        'from io import StringIO\nimport pandas as pd\n\ndef summarize(text):\n    # Parse, validate, deduplicate, and summarize.\n    pass\n',
        'from io import StringIO\nimport pandas as pd\n\ndef summarize(text):\n    data = pd.read_csv(StringIO(text))\n    data["units"] = pd.to_numeric(data["units"], errors="raise")\n    if data["units"].isna().any():\n        raise ValueError("Missing quantity")\n    data = data.sort_values("version").drop_duplicates("event_id", keep="last")\n    assert data["event_id"].is_unique\n    return data.groupby("shop")["units"].sum().sort_index()',
        'sample = "event_id,version,shop,units\\n1,1,west,2\\n2,1,east,5\\n1,2,west,7\\n3,1,east,3\\n"\nresult = summarize(sample)\nassert isinstance(result, pd.Series) and result.to_dict() == {"east": 8, "west": 7}, "Keep latest event versions and aggregate by shop."\nassert result.index.tolist() == ["east", "west"], "Sort the result labels."\nsecond = "event_id,version,shop,units\\n4,1,north,9\\n5,1,north,2\\n"\nassert summarize(second).to_dict() == {"north": 11}, "Use the function input rather than a fixed dataset."\nassert summarize(sample).equals(result), "Repeated calls should reproduce the result."\ntry:\n    summarize("event_id,version,shop,units\\n6,1,south,invalid\\n")\nexcept (ValueError, TypeError):\n    pass\nelse:\n    raise AssertionError("Reject invalid numeric quantities rather than silently changing them.")\ntry:\n    summarize("event_id,version,shop,units\\n7,1,south,\\n")\nexcept (ValueError, TypeError):\n    pass\nelse:\n    raise AssertionError("Reject missing quantities rather than assuming zero.")',
        'The function makes the input contract, numeric validation, duplicate policy, and grouping rule part of a reusable analysis.',
        'Use read_csv(StringIO(text)), to_numeric(errors="raise"), sort/drop_duplicates, then groupby/sum/sort_index.',
      ),
    ],
    [
      [
        'What makes an analysis pipeline repeatable?',
        'Explicit input data, declared transformations and validation rules, and a returned result independent of hidden state.',
      ],
      [
        'Why validate observation keys before reporting totals?',
        'Repeated or missing identities can change what one row means and cause totals to count the wrong observations.',
      ],
    ],
  ),
].map((item, index) => ({ ...item, order: index }));

export const dataAnalysisCatalog: CurriculumCatalog = {
  courses: [
    {
      id: courseId,
      title: 'Python for data analysis',
      description:
        'Analyze original small datasets with NumPy and pandas: clean, join, reshape, aggregate, and build a repeatable report.',
      domain: 'programming',
      skillIds: skills.map((item) => item.id),
    },
  ],
  units,
  skills,
};
