/** Direct prerequisites only: each edge names a rule or construct the skill's lesson, example, or assessment actually uses. Topic stages are display metadata and impose no order. */
export const rustPrerequisites: Record<string, string[]> = {
  'rust-main': [],
  'rust-format': ['rust-main'],
  'rust-bindings': ['rust-parameters'],
  'rust-scope': ['rust-bindings'],
  'rust-integers': ['rust-tuples-arrays'],
  'rust-floats': ['rust-integers', 'rust-booleans'],
  'rust-booleans': ['rust-parameters'],
  'rust-tuples-arrays': ['rust-parameters'],
  'rust-if': ['rust-booleans'],
  'rust-match': ['rust-static'],
  'rust-loop': ['rust-bindings', 'rust-integers', 'rust-if'],
  'rust-ranges': ['rust-bindings'],
  'rust-parameters': ['rust-returns'],
  'rust-returns': ['rust-main'],
  'rust-unit': ['rust-scope', 'rust-tuples-arrays'],
  'rust-recursion': ['rust-floats', 'rust-if'],
  'rust-moves': ['rust-format', 'rust-parameters'],
  'rust-copy': ['rust-moves'],
  'rust-clone': ['rust-bindings', 'rust-tuples-arrays', 'rust-moves'],
  'rust-drop': ['rust-moves'],
  'rust-shared-borrow': ['rust-moves'],
  'rust-mutable-borrow': ['rust-unit', 'rust-shared-borrow'],
  'rust-borrow-ends': ['rust-mutable-borrow', 'rust-string-conversion'],
  'rust-slices': ['rust-tuples-arrays', 'rust-ranges', 'rust-shared-borrow'],
  'rust-utf8-bytes': ['rust-chars'],
  'rust-chars': ['rust-string-conversion', 'rust-option'],
  'rust-string-boundaries': ['rust-utf8-bytes'],
  'rust-string-conversion': ['rust-bindings', 'rust-shared-borrow'],
  'rust-struct-fields': ['rust-parameters'],
  'rust-struct-update': [
    'rust-booleans',
    'rust-tuples-arrays',
    'rust-struct-fields',
  ],
  'rust-methods': [
    'rust-tuples-arrays',
    'rust-shared-borrow',
    'rust-struct-fields',
  ],
  'rust-associated-functions': ['rust-methods'],
  'rust-enum-variants': ['rust-if'],
  'rust-enum-data': ['rust-match', 'rust-enum-variants'],
  'rust-if-let': ['rust-enum-data', 'rust-option'],
  'rust-destructure': ['rust-enum-data', 'rust-option'],
  'rust-option': ['rust-slices'],
  'rust-option-map': ['rust-option'],
  'rust-option-and-then': [
    'rust-enum-data',
    'rust-option-map',
    'rust-panic-contracts',
  ],
  'rust-option-transpose': ['rust-option-map', 'rust-question-mark'],
  'rust-result': ['rust-floats', 'rust-enum-data'],
  'rust-result-map': ['rust-option-map', 'rust-result'],
  'rust-map-error': ['rust-result-map'],
  'rust-question-mark': ['rust-result'],
  'rust-vec-push': ['rust-option'],
  'rust-vec-get': ['rust-option'],
  'rust-vec-retain': [
    'rust-booleans',
    'rust-mutable-borrow',
    'rust-option-map',
    'rust-vec-push',
  ],
  'rust-vec-extend': ['rust-vec-push', 'rust-iterator-lazy'],
  'rust-map-entry': ['rust-map-lookup'],
  'rust-map-lookup': ['rust-destructure', 'rust-map-filter'],
  'rust-hash-set': ['rust-map-filter'],
  'rust-btree-range': ['rust-map-lookup'],
  'rust-generic-functions': ['rust-moves'],
  'rust-generic-structs': ['rust-struct-fields', 'rust-generic-functions'],
  'rust-trait-bounds': ['rust-if', 'rust-generic-functions', 'rust-trait-impl'],
  'rust-where': ['rust-clone', 'rust-trait-bounds'],
  'rust-trait-impl': ['rust-methods'],
  'rust-default-method': ['rust-trait-impl'],
  'rust-associated-types': ['rust-trait-impl'],
  'rust-trait-objects': ['rust-trait-impl'],
  'rust-lifetime-elision': ['rust-string-conversion'],
  'rust-lifetime-explicit': ['rust-if', 'rust-lifetime-elision'],
  'rust-borrowed-struct': ['rust-methods', 'rust-lifetime-explicit'],
  'rust-static': ['rust-if', 'rust-string-conversion'],
  'rust-closure-capture': ['rust-shared-borrow'],
  'rust-fn-bound': ['rust-trait-bounds', 'rust-closure-capture'],
  'rust-fn-mut': ['rust-mutable-borrow', 'rust-slices', 'rust-fn-bound'],
  'rust-fn-once': ['rust-fn-bound'],
  'rust-iterator-lazy': ['rust-slices', 'rust-closure-capture'],
  'rust-map-filter': [
    'rust-booleans',
    'rust-mutable-borrow',
    'rust-vec-push',
    'rust-iterator-lazy',
  ],
  'rust-fold': ['rust-iterator-lazy'],
  'rust-collect': ['rust-question-mark', 'rust-map-filter'],
  'rust-module-privacy': ['rust-returns'],
  'rust-use': ['rust-map-filter'],
  'rust-reexport': ['rust-module-privacy', 'rust-use'],
  'rust-module-paths': ['rust-module-privacy'],
  'rust-package-name': ['rust-string-conversion'],
  'rust-semver': ['rust-option', 'rust-question-mark'],
  'rust-cfg': ['rust-returns'],
  'rust-test-contract': [
    'rust-mutable-borrow',
    'rust-fold',
    'rust-checked-arithmetic',
  ],
  'rust-boundary-tests': [
    'rust-booleans',
    'rust-closure-capture',
    'rust-checked-arithmetic',
  ],
  'rust-table-tests': ['rust-destructure'],
  'rust-invariants': ['rust-map-filter'],
  'rust-panic-contracts': ['rust-option'],
  'rust-box': ['rust-mutable-borrow'],
  'rust-rc': ['rust-clone', 'rust-shared-borrow'],
  'rust-arc': ['rust-rc'],
  'rust-weak': ['rust-booleans', 'rust-drop', 'rust-option', 'rust-rc'],
  'rust-cell': ['rust-copy', 'rust-shared-borrow'],
  'rust-refcell': ['rust-clone', 'rust-borrow-ends', 'rust-vec-push'],
  'rust-try-borrow': ['rust-drop', 'rust-result', 'rust-refcell'],
  'rust-cow': ['rust-enum-data', 'rust-borrowed-struct', 'rust-package-name'],
  'rust-thread-move': ['rust-fn-once'],
  'rust-scoped-threads': ['rust-iterator-lazy', 'rust-thread-move'],
  'rust-mutex': ['rust-mutable-borrow', 'rust-arc', 'rust-thread-move'],
  'rust-channels': ['rust-destructure', 'rust-thread-move'],
  'rust-atomic-load-store': ['rust-use', 'rust-thread-move'],
  'rust-atomic-fetch': ['rust-atomic-load-store'],
  'rust-compare-exchange': ['rust-result', 'rust-atomic-load-store'],
  'rust-acquire-release': ['rust-atomic-load-store'],
  'rust-send': ['rust-static', 'rust-thread-move'],
  'rust-sync': ['rust-mutable-borrow', 'rust-scoped-threads', 'rust-send'],
  'rust-arc-mutex': ['rust-vec-push', 'rust-mutex'],
  'rust-deadlock-scope': ['rust-mutex'],
  'rust-future-ready': ['rust-enum-data', 'rust-trait-impl', 'rust-use'],
  'rust-future-pending': [
    'rust-associated-types',
    'rust-borrowed-struct',
    'rust-future-pin',
  ],
  'rust-future-pin': ['rust-box', 'rust-future-ready'],
  'rust-await': ['rust-future-pin'],
  'rust-raw-pointers': ['rust-scope', 'rust-booleans', 'rust-shared-borrow'],
  'rust-raw-dereference': [
    'rust-if',
    'rust-mutable-borrow',
    'rust-option',
    'rust-raw-pointers',
  ],
  'rust-raw-slices': ['rust-iterator-lazy', 'rust-raw-dereference'],
  'rust-unsafe-wrapper': ['rust-destructure', 'rust-raw-slices'],
  'rust-repr-c': ['rust-struct-fields'],
  'rust-extern-abi': ['rust-parameters'],
  'rust-c-strings': ['rust-option-map', 'rust-result', 'rust-closure-capture'],
  'rust-byte-order': ['rust-option', 'rust-question-mark'],
  'rust-capacity': ['rust-booleans', 'rust-vec-push'],
  'rust-layout': ['rust-tuples-arrays', 'rust-repr-c'],
  'rust-checked-arithmetic': ['rust-option'],
  'rust-sort-dedup': ['rust-vec-push'],
  'rust-binary-search': ['rust-integers', 'rust-destructure'],
  'rust-two-pointers': ['rust-floats', 'rust-destructure'],
  'rust-bfs': ['rust-if-let', 'rust-vec-push'],
  'rust-heap-selection': ['rust-if', 'rust-map-filter', 'rust-sort-dedup'],
  'rust-frame-header': ['rust-vec-get', 'rust-byte-order'],
  'rust-frame-payload': ['rust-checked-arithmetic', 'rust-frame-header'],
  'rust-frame-encode': [
    'rust-vec-extend',
    'rust-capacity',
    'rust-frame-header',
  ],
  'rust-frame-stream': ['rust-vec-push', 'rust-frame-payload'],
};
