/** Direct prerequisites only: each edge names an operation the skill's lesson, example, or assessment actually uses. Topic stages are display metadata and impose no order. */
export const cppPrerequisites: Record<string, string[]> = {
  'cpp-integer-values': [],
  'cpp-arithmetic': ['cpp-integer-values'],
  'cpp-explicit-casts': ['cpp-arithmetic'],
  'cpp-values': ['cpp-arithmetic', 'cpp-if-branches', 'cpp-logical-operators'],
  'cpp-bool-values': ['cpp-integer-values'],
  'cpp-unsigned-wrap': ['cpp-values'],
  'cpp-scoped-enums': ['cpp-conditional-operator'],
  'cpp-types': ['cpp-reference-alias'],
  'cpp-char-values': ['cpp-integer-values'],
  'cpp-sizeof-bytes': ['cpp-char-values'],
  'cpp-fixed-width-integers': [
    'cpp-sizeof-bytes',
    'cpp-unsigned-wrap',
    'cpp-explicit-casts',
  ],
  'cpp-type-facts': ['cpp-fixed-width-integers'],
  'cpp-bit-shifts': ['cpp-unsigned-wrap'],
  'cpp-bit-masks': ['cpp-unsigned-wrap'],
  'cpp-bit-flags': ['cpp-bit-shifts', 'cpp-bit-masks'],
  'cpp-bits': ['cpp-bit-shifts', 'cpp-bit-masks', 'cpp-fixed-width-integers'],
  'cpp-if-branches': ['cpp-bool-values'],
  'cpp-for-bounds': ['cpp-bool-values'],
  'cpp-while-progress': ['cpp-arithmetic', 'cpp-bool-values'],
  'cpp-control': [
    'cpp-explicit-casts',
    'cpp-for-bounds',
    'cpp-vector-elements',
  ],
  'cpp-logical-operators': ['cpp-bool-values'],
  'cpp-short-circuit': ['cpp-logical-operators', 'cpp-arithmetic'],
  'cpp-conditional-operator': ['cpp-bool-values'],
  'cpp-logic': ['cpp-logical-operators'],
  'cpp-std-array': ['cpp-for-bounds'],
  'cpp-range-for': ['cpp-std-array'],
  'cpp-loop-exits': ['cpp-if-branches', 'cpp-range-for'],
  'cpp-arrays': ['cpp-range-for', 'cpp-types'],
  'cpp-return-values': ['cpp-integer-values'],
  'cpp-function-overloads': ['cpp-explicit-casts', 'cpp-return-values'],
  'cpp-default-arguments': ['cpp-return-values'],
  'cpp-functions': ['cpp-reference-parameter', 'cpp-aggregate-init'],
  'cpp-reference-alias': ['cpp-integer-values'],
  'cpp-reference-parameter': ['cpp-return-values', 'cpp-reference-alias'],
  'cpp-reference-reseat': ['cpp-reference-alias'],
  'cpp-references': ['cpp-reference-parameter', 'cpp-pointer-address'],
  'cpp-pointer-address': ['cpp-return-values'],
  'cpp-nullptr-guard': ['cpp-pointer-address', 'cpp-conditional-operator'],
  'cpp-pointer-reseat': ['cpp-pointer-address'],
  'cpp-pointers': [
    'cpp-types',
    'cpp-functions',
    'cpp-pointer-address',
    'cpp-std-array',
  ],
  'cpp-span-size': ['cpp-pointers', 'cpp-range-for'],
  'cpp-span-subview': [
    'cpp-explicit-casts',
    'cpp-unsigned-wrap',
    'cpp-span-size',
  ],
  'cpp-string-view': ['cpp-string-size'],
  'cpp-views': ['cpp-string-view'],
  'cpp-aggregate-init': ['cpp-return-values'],
  'cpp-constructor-init': ['cpp-aggregate-init'],
  'cpp-destructor-scope': ['cpp-reference-alias', 'cpp-aggregate-init'],
  'cpp-lifetime': ['cpp-destructor-scope'],
  'cpp-member-functions': ['cpp-aggregate-init'],
  'cpp-const-member-functions': ['cpp-member-functions'],
  'cpp-const-correctness': [
    'cpp-const-member-functions',
    'cpp-functions',
    'cpp-bool-values',
  ],
  'cpp-members': [
    'cpp-const-member-functions',
    'cpp-constructor-init',
    'cpp-if-branches',
  ],
  'cpp-scope-resource': [
    'cpp-if-branches',
    'cpp-constructor-init',
    'cpp-destructor-scope',
  ],
  'cpp-exception-cleanup': ['cpp-scope-resource', 'cpp-throw-catch'],
  'cpp-noncopy-owner': ['cpp-scope-resource', 'cpp-type-facts'],
  'cpp-raii': ['cpp-destructor-scope'],
  'cpp-unique-allocation': [
    'cpp-types',
    'cpp-pointer-address',
    'cpp-scope-resource',
  ],
  'cpp-unique-transfer': [
    'cpp-nullptr-guard',
    'cpp-unique-allocation',
    'cpp-move-cast',
  ],
  'cpp-shared-ownership': ['cpp-unique-allocation'],
  'cpp-smart-pointers': [
    'cpp-explicit-casts',
    'cpp-shared-ownership',
    'cpp-logical-operators',
  ],
  'cpp-lvalue-rvalue': ['cpp-function-overloads', 'cpp-reference-alias'],
  'cpp-move-cast': ['cpp-functions', 'cpp-lvalue-rvalue'],
  'cpp-move-member': ['cpp-unique-transfer'],
  'cpp-move': ['cpp-move-member', 'cpp-exceptions', 'cpp-type-facts'],
  'cpp-independent-copy': ['cpp-types', 'cpp-vector-elements'],
  'cpp-rule-zero': ['cpp-independent-copy'],
  'cpp-copy-assignment': ['cpp-independent-copy'],
  'cpp-value-semantics': ['cpp-independent-copy'],
  'cpp-string-size': ['cpp-explicit-casts', 'cpp-functions'],
  'cpp-string-append': ['cpp-string-size', 'cpp-char-values'],
  'cpp-string-find': [
    'cpp-types',
    'cpp-string-size',
    'cpp-conditional-operator',
    'cpp-char-values',
  ],
  'cpp-strings': [
    'cpp-if-branches',
    'cpp-pointers',
    'cpp-string-view',
    'cpp-logical-operators',
  ],
  'cpp-vector-elements': [
    'cpp-unsigned-wrap',
    'cpp-functions',
    'cpp-conditional-operator',
  ],
  'cpp-vector-push': ['cpp-explicit-casts', 'cpp-vector-elements'],
  'cpp-vector-reserve': ['cpp-vector-push'],
  'cpp-vectors': ['cpp-explicit-casts', 'cpp-iterator-range', 'cpp-range-for'],
  'cpp-iterator-range': ['cpp-pointers', 'cpp-vector-elements'],
  'cpp-iterator-distance': ['cpp-explicit-casts', 'cpp-iterator-range'],
  'cpp-reallocation-invalidation': ['cpp-vector-reserve', 'cpp-iterator-range'],
  'cpp-iterators': ['cpp-vectors', 'cpp-reallocation-invalidation'],
  'cpp-pair-members': ['cpp-arithmetic'],
  'cpp-pair-ordering': ['cpp-pair-members', 'cpp-logical-operators'],
  'cpp-structured-bindings': ['cpp-pair-members', 'cpp-types', 'cpp-range-for'],
  'cpp-pairs': [
    'cpp-structured-bindings',
    'cpp-pair-ordering',
    'cpp-if-branches',
  ],
  'cpp-map-find': ['cpp-iterator-range', 'cpp-pair-members'],
  'cpp-map-insert': ['cpp-map-find'],
  'cpp-unordered-frequency': ['cpp-map-find', 'cpp-range-for'],
  'cpp-maps': ['cpp-map-find'],
  'cpp-set-membership': ['cpp-explicit-casts', 'cpp-iterator-range'],
  'cpp-set-lower-bound': ['cpp-set-membership'],
  'cpp-heap-top': ['cpp-iterator-range'],
  'cpp-sets': ['cpp-heap-top'],
  'cpp-sort-order': ['cpp-iterator-range'],
  'cpp-binary-search': ['cpp-sort-order'],
  'cpp-accumulate-seed': ['cpp-iterator-range'],
  'cpp-algorithms': ['cpp-vectors'],
  'cpp-lambda-value-capture': ['cpp-types', 'cpp-return-values'],
  'cpp-lambda-reference-capture': ['cpp-lambda-value-capture'],
  'cpp-lambda-predicate': [
    'cpp-explicit-casts',
    'cpp-iterator-range',
    'cpp-lambda-value-capture',
  ],
  'cpp-lambdas': ['cpp-unique-transfer'],
  'cpp-function-template': [
    'cpp-function-overloads',
    'cpp-conditional-operator',
  ],
  'cpp-template-deduction': ['cpp-function-template'],
  'cpp-class-template': ['cpp-aggregate-init', 'cpp-function-template'],
  'cpp-templates': ['cpp-move-cast', 'cpp-template-deduction'],
  'cpp-integral-concept': ['cpp-function-template'],
  'cpp-requires-expression': ['cpp-vector-elements', 'cpp-integral-concept'],
  'cpp-if-constexpr': ['cpp-function-template', 'cpp-type-facts'],
  'cpp-concepts': ['cpp-integral-concept'],
  'cpp-constexpr-function': ['cpp-static-assert'],
  'cpp-static-assert': ['cpp-return-values', 'cpp-fixed-width-integers'],
  'cpp-consteval-function': ['cpp-constexpr-function', 'cpp-bit-shifts'],
  'cpp-constexpr': [
    'cpp-types',
    'cpp-constexpr-function',
    'cpp-std-array',
    'cpp-conditional-operator',
  ],
  'cpp-optional-value': ['cpp-if-branches'],
  'cpp-optional-search': [
    'cpp-explicit-casts',
    'cpp-types',
    'cpp-for-bounds',
    'cpp-vector-elements',
    'cpp-optional-value',
  ],
  'cpp-variant-alternatives': [
    'cpp-if-branches',
    'cpp-string-size',
    'cpp-conditional-operator',
  ],
  'cpp-optional': [
    'cpp-lambda-value-capture',
    'cpp-if-constexpr',
    'cpp-variant-alternatives',
  ],
  'cpp-throw-catch': ['cpp-if-branches', 'cpp-functions'],
  'cpp-bounds-exception': ['cpp-vector-elements', 'cpp-throw-catch'],
  'cpp-strong-guarantee': ['cpp-throw-catch'],
  'cpp-exceptions': ['cpp-throw-catch', 'cpp-logical-operators'],
  'cpp-virtual-dispatch': [
    'cpp-constructor-init',
    'cpp-destructor-scope',
    'cpp-const-correctness',
  ],
  'cpp-virtual-destruction': ['cpp-unique-allocation', 'cpp-virtual-dispatch'],
  'cpp-avoid-slicing': ['cpp-virtual-dispatch'],
  'cpp-polymorphism': ['cpp-virtual-dispatch'],
  'cpp-declaration-definition': ['cpp-return-values'],
  'cpp-namespace-qualified': ['cpp-return-values'],
  'cpp-internal-linkage': [
    'cpp-declaration-definition',
    'cpp-namespace-qualified',
  ],
  'cpp-build': ['cpp-constexpr-function', 'cpp-internal-linkage'],
  'cpp-assert-contract': ['cpp-bool-values', 'cpp-return-values'],
  'cpp-boundary-case': ['cpp-vector-elements', 'cpp-assert-contract'],
  'cpp-property-test': [
    'cpp-independent-copy',
    'cpp-iterator-range',
    'cpp-assert-contract',
  ],
  'cpp-testing': [
    'cpp-explicit-casts',
    'cpp-assert-contract',
    'cpp-logical-operators',
  ],
  'cpp-thread-join': ['cpp-lambda-reference-capture'],
  'cpp-thread-input-copy': ['cpp-thread-join'],
  'cpp-parallel-partitions': ['cpp-thread-join'],
  'cpp-threads': ['cpp-destructor-scope', 'cpp-thread-join'],
  'cpp-lock-guard': ['cpp-scope-resource', 'cpp-parallel-partitions'],
  'cpp-mutex-counter': ['cpp-for-bounds', 'cpp-lock-guard'],
  'cpp-scoped-two-locks': ['cpp-lock-guard'],
  'cpp-mutex': ['cpp-lock-guard', 'cpp-logical-operators'],
  'cpp-wait-predicate': ['cpp-mutex'],
  'cpp-notify-after-state': ['cpp-wait-predicate'],
  'cpp-wait-unlocks': ['cpp-notify-after-state'],
  'cpp-condition-variables': ['cpp-wait-predicate', 'cpp-deque-front-back'],
  'cpp-atomic-load-store': ['cpp-parallel-partitions'],
  'cpp-atomic-fetch-add': ['cpp-atomic-load-store'],
  'cpp-atomic-compare-exchange': ['cpp-atomic-load-store'],
  'cpp-atomics': ['cpp-for-bounds', 'cpp-relaxed-counter'],
  'cpp-relaxed-counter': ['cpp-atomic-fetch-add'],
  'cpp-release-acquire': [
    'cpp-while-progress',
    'cpp-relaxed-counter',
    'cpp-logical-operators',
  ],
  'cpp-seq-cst': ['cpp-release-acquire'],
  'cpp-memory-ordering': [
    'cpp-while-progress',
    'cpp-atomic-compare-exchange',
    'cpp-relaxed-counter',
    'cpp-logical-operators',
  ],
  'cpp-async-result': ['cpp-thread-join'],
  'cpp-promise-value': ['cpp-async-result'],
  'cpp-future-exception': ['cpp-throw-catch', 'cpp-async-result'],
  'cpp-futures': ['cpp-promise-value'],
  'cpp-page-offset': ['cpp-unsigned-wrap'],
  'cpp-page-translation': [
    'cpp-vector-elements',
    'cpp-constexpr-function',
    'cpp-page-offset',
    'cpp-short-circuit',
  ],
  'cpp-aligned-size': ['cpp-unsigned-wrap', 'cpp-types'],
  'cpp-addressing': ['cpp-lambda-reference-capture'],
  'cpp-contiguous-traversal': [
    'cpp-pointers',
    'cpp-vector-elements',
    'cpp-range-for',
  ],
  'cpp-cache-line-model': ['cpp-unsigned-wrap'],
  'cpp-row-major-index': ['cpp-vector-elements', 'cpp-short-circuit'],
  'cpp-locality': [
    'cpp-explicit-casts',
    'cpp-for-bounds',
    'cpp-vector-elements',
  ],
  'cpp-alignas-contract': ['cpp-aggregate-init'],
  'cpp-padded-counter': ['cpp-atomic-load-store', 'cpp-alignas-contract'],
  'cpp-layout-spacing': [
    'cpp-arithmetic',
    'cpp-padded-counter',
    'cpp-logical-operators',
    'cpp-sizeof-bytes',
  ],
  'cpp-false-sharing': ['cpp-cache-line-model', 'cpp-short-circuit'],
  'cpp-duration-count': ['cpp-integer-values'],
  'cpp-duration-cast': ['cpp-duration-count', 'cpp-arithmetic'],
  'cpp-time-points': ['cpp-duration-cast'],
  'cpp-chrono': ['cpp-time-points', 'cpp-bool-values'],
  'cpp-elapsed-duration': ['cpp-arithmetic', 'cpp-conditional-operator'],
  'cpp-median-samples': ['cpp-explicit-casts', 'cpp-sort-order'],
  'cpp-nearest-rank-percentile': ['cpp-median-samples'],
  'cpp-measurement': [
    'cpp-if-branches',
    'cpp-for-bounds',
    'cpp-logical-operators',
  ],
  'cpp-book-add-level': ['cpp-unordered-frequency', 'cpp-structured-bindings'],
  'cpp-book-cancel-level': [
    'cpp-if-branches',
    'cpp-logical-operators',
    'cpp-conditional-operator',
  ],
  'cpp-book-best-bid': ['cpp-maps'],
  'cpp-order-book': ['cpp-book-best-bid'],
  'cpp-ring-wrap': ['cpp-arithmetic', 'cpp-if-branches', 'cpp-logic'],
  'cpp-ring-bounded-push': [
    'cpp-explicit-casts',
    'cpp-vector-elements',
    'cpp-ring-wrap',
    'cpp-loop-exits',
  ],
  'cpp-ring-fifo-pop': ['cpp-while-progress', 'cpp-ring-bounded-push'],
  'cpp-ring-buffer': ['cpp-release-acquire', 'cpp-ring-fifo-pop'],
  'cpp-big-endian-word': [
    'cpp-bit-shifts',
    'cpp-bit-masks',
    'cpp-fixed-width-integers',
  ],
  'cpp-frame-length': ['cpp-span-size', 'cpp-big-endian-word'],
  'cpp-sequence-gap': ['cpp-unsigned-wrap'],
  'cpp-protocol': [
    'cpp-unsigned-wrap',
    'cpp-for-bounds',
    'cpp-while-progress',
    'cpp-string-view',
    'cpp-string-append',
    'cpp-short-circuit',
  ],
  'cpp-book-imbalance': [
    'cpp-explicit-casts',
    'cpp-if-branches',
    'cpp-logical-operators',
    'cpp-conditional-operator',
  ],
  'cpp-notional-limit': ['cpp-explicit-casts', 'cpp-values'],
  'cpp-position-bound': ['cpp-notional-limit', 'cpp-logic'],
  'cpp-risk': ['cpp-bool-values'],
  'cpp-deque-front-back': ['cpp-vector-push'],
  'cpp-deque-pop': ['cpp-deque-front-back'],
  'cpp-queue-fifo': ['cpp-deque-pop', 'cpp-range-for'],
  'cpp-deque': ['cpp-deque-front-back', 'cpp-loop-exits'],
  'cpp-function-object': ['cpp-const-member-functions'],
  'cpp-std-function': ['cpp-lambda-value-capture', 'cpp-function-object'],
  'cpp-empty-callback': [
    'cpp-if-branches',
    'cpp-std-function',
    'cpp-conditional-operator',
  ],
  'cpp-callbacks': ['cpp-lambdas', 'cpp-std-function'],
  'cpp-backpressure': ['cpp-deque'],
  'cpp-idempotent-message': [
    'cpp-map-insert',
    'cpp-set-membership',
    'cpp-range-for',
  ],
  'cpp-replay-events': [
    'cpp-vector-elements',
    'cpp-structured-bindings',
    'cpp-char-values',
  ],
  'cpp-architecture': ['cpp-replay-events'],
  'cpp-tie-break-order': [
    'cpp-sort-order',
    'cpp-lambda-predicate',
    'cpp-pair-members',
  ],
  'cpp-integer-money': ['cpp-notional-limit'],
  'cpp-seeded-engine': ['cpp-unsigned-wrap', 'cpp-for-bounds'],
  'cpp-determinism': [
    'cpp-position-bound',
    'cpp-idempotent-message',
    'cpp-structured-bindings',
    'cpp-loop-exits',
  ],
};
