import {
  mkdir,
  readdir,
  copyFile,
  readFile,
  writeFile,
  rename,
  rm,
} from 'node:fs/promises';
import { join } from 'node:path';
import { createHash } from 'node:crypto';

const source = 'node_modules/pyodide';
const root = 'public/pyodide';
const digest = (bytes) => createHash('sha256').update(bytes).digest('hex');

/** Writes through a temporary name, so a reader never sees half a file. */
async function writeAtomically(destination, bytes) {
  await writeFile(`${destination}.download`, bytes);
  await rename(`${destination}.download`, destination);
}

/** A verified copy of a wheel left by an earlier layout or package set. */
async function previousCopy(fileName, sha256, entries) {
  const candidates = [
    join(root, fileName),
    ...entries.map((entry) => join(root, entry, fileName)),
  ];
  for (const candidate of candidates) {
    try {
      if (digest(await readFile(candidate)) === sha256) return candidate;
    } catch (error) {
      if (error.code !== 'ENOENT' && error.code !== 'ENOTDIR') throw error;
    }
  }
  return undefined;
}

try {
  const files = await readdir(source);
  const { version } = JSON.parse(
    await readFile(join(source, 'package.json'), 'utf8'),
  );
  // Official Pyodide wheels and their transitive dependencies, pinned by its lockfile.
  const lock = JSON.parse(
    await readFile(join(source, 'pyodide-lock.json'), 'utf8'),
  );
  const required = new Set();
  function include(name) {
    if (required.has(name)) return;
    const item = lock.packages[name];
    if (!item) throw new Error(`Unknown Pyodide dependency: ${name}`);
    required.add(name);
    item.depends.forEach(include);
  }
  ['numpy', 'pandas', 'scikit-learn'].forEach(include);
  // Restrict import-driven loading to packages we actually serve locally.
  const served = JSON.stringify({
    ...lock,
    packages: Object.fromEntries(
      [...required].map((name) => [name, lock.packages[name]]),
    ),
  });
  // Browsers cache everything under this directory as immutable
  // (public/_headers), so its name changes whenever a file in it could: the
  // Pyodide version names the runtime, and the served lockfile pins every
  // wheel by its hash.
  const directory = `${version}-${digest(served).slice(0, 10)}`;
  const target = join(root, directory);
  await mkdir(target, { recursive: true });
  const entries = (await readdir(root)).filter((entry) => entry !== directory);

  for (const file of files) {
    if (/\.(mjs|wasm|zip|json)$/.test(file) || file === 'LICENSE') {
      await copyFile(join(source, file), join(target, file));
    }
  }
  await Promise.all(
    [...required].map(async (name) => {
      const item = lock.packages[name];
      const destination = join(target, item.file_name);
      try {
        if (digest(await readFile(destination)) === item.sha256) return;
      } catch (error) {
        if (error.code !== 'ENOENT') throw error;
      }
      const previous = await previousCopy(item.file_name, item.sha256, entries);
      if (previous) {
        await copyFile(previous, destination);
        return;
      }
      const response = await fetch(
        `https://cdn.jsdelivr.net/pyodide/v${version}/full/${item.file_name}`,
      );
      if (!response.ok)
        throw new Error(`Could not fetch ${name}: HTTP ${response.status}`);
      const bytes = Buffer.from(await response.arrayBuffer());
      if (digest(bytes) !== item.sha256)
        throw new Error(`Pyodide integrity check failed: ${name}`);
      await writeAtomically(destination, bytes);
      console.log(`Prepared Python package: ${name} ${item.version}`);
    }),
  );
  await writeFile(join(target, 'pyodide-lock.json'), served);
  // The worker imports this small module, which browsers revalidate on every
  // load, to find the current immutable directory.
  await writeAtomically(
    join(root, 'current.mjs'),
    [
      '// Generated by scripts/copy-python.mjs. Do not edit.',
      `export const indexURL = '/pyodide/${directory}/';`,
      `export { loadPyodide } from './${directory}/pyodide.mjs';`,
      '',
    ].join('\n'),
  );
  // Only the current runtime is deployed.
  await Promise.all(
    entries
      .filter((entry) => entry !== 'current.mjs')
      .map((entry) => rm(join(root, entry), { recursive: true, force: true })),
  );
} catch (error) {
  if (error.code !== 'ENOENT') throw error;
}
